python ./cmsdetect.py 1 北海道 http://www.pref.hokkaido.lg.jp/
python ./cmsdetect.py 1 愛別町 http://www.town.aibetsu.hokkaido.jp/
python ./cmsdetect.py 1 赤井川村 https://www.akaigawa.com/
python ./cmsdetect.py 1 赤平市 https://www.city.akabira.hokkaido.jp/
python ./cmsdetect.py 1 旭川市 https://www.city.asahikawa.hokkaido.jp/
python ./cmsdetect.py 1 芦別市 https://www.city.ashibetsu.hokkaido.jp/
python ./cmsdetect.py 1 足寄町 https://www.town.ashoro.hokkaido.jp/
python ./cmsdetect.py 1 厚岸町 https://www.akkeshi-town.jp/
python ./cmsdetect.py 1 厚沢部町 https://www.town.assabu.lg.jp/
python ./cmsdetect.py 1 厚真町 http://www.town.atsuma.lg.jp/office/
python ./cmsdetect.py 1 網走市 https://www.city.abashiri.hokkaido.jp/
python ./cmsdetect.py 1 安平町 https://www.town.abira.lg.jp/
python ./cmsdetect.py 1 池田町 https://www.town.hokkaido-ikeda.lg.jp/
python ./cmsdetect.py 1 石狩市 http://www.city.ishikari.hokkaido.jp/
python ./cmsdetect.py 1 今金町 https://www.town.imakane.lg.jp/
python ./cmsdetect.py 1 岩内町 https://www.town.iwanai.hokkaido.jp/
python ./cmsdetect.py 1 岩見沢市 https://www.city.iwamizawa.hokkaido.jp/
python ./cmsdetect.py 1 歌志内市 http://www.city.utashinai.hokkaido.jp/
python ./cmsdetect.py 1 浦臼町 https://www.town.urausu.hokkaido.jp/
python ./cmsdetect.py 1 浦河町 https://www.town.urakawa.hokkaido.jp/
python ./cmsdetect.py 1 浦幌町 http://www.urahoro.jp/
python ./cmsdetect.py 1 雨竜町 http://www.town.uryu.hokkaido.jp/
python ./cmsdetect.py 1 江差町 https://www.hokkaido-esashi.jp/
python ./cmsdetect.py 1 枝幸町 http://www.esashi.jp/
python ./cmsdetect.py 1 恵庭市 https://www.city.eniwa.hokkaido.jp/
python ./cmsdetect.py 1 江別市 http://www.city.ebetsu.hokkaido.jp/
python ./cmsdetect.py 1 えりも町 http://www.town.erimo.lg.jp/https://www.town.erimo.lg.jp/
python ./cmsdetect.py 1 遠軽町 https://engaru.jp/
python ./cmsdetect.py 1 遠別町 http://www.town.embetsu.hokkaido.jp/
python ./cmsdetect.py 1 雄武町 http://www.town.oumu.hokkaido.jp/
python ./cmsdetect.py 1 大空町 http://www.town.ozora.hokkaido.jp/
python ./cmsdetect.py 1 奥尻町 https://www.town.okushiri.lg.jp/
python ./cmsdetect.py 1 置戸町 http://www.town.oketo.hokkaido.jp/
python ./cmsdetect.py 1 興部町 https://www.town.okoppe.lg.jp/cms/
python ./cmsdetect.py 1 長万部町 http://www.town.oshamambe.lg.jp/
python ./cmsdetect.py 1 小樽市 https://www.city.otaru.lg.jp/
python ./cmsdetect.py 1 音威子府村 http://www.vill.otoineppu.hokkaido.jp/
python ./cmsdetect.py 1 音更町 https://www.town.otofuke.hokkaido.jp/
python ./cmsdetect.py 1 乙部町 https://www.town.otobe.lg.jp/
python ./cmsdetect.py 1 帯広市 https://www.town.otofuke.hokkaido.jp/
python ./cmsdetect.py 1 小平町 http://www.town.obira.hokkaido.jp/
python ./cmsdetect.py 1 上川町 https://www.town.hokkaido-kamikawa.lg.jp/
python ./cmsdetect.py 1 上士幌町 https://www.kamishihoro.jp/
python ./cmsdetect.py 1 上砂川町 http://town.kamisunagawa.hokkaido.jp/
python ./cmsdetect.py 1 上ノ国町 http://www.town.kaminokuni.lg.jp/
python ./cmsdetect.py 1 上富良野町 http://www.town.kamifurano.hokkaido.jp/
python ./cmsdetect.py 1 神恵内村 https://www.vill.kamoenai.hokkaido.jp/
python ./cmsdetect.py 1 木古内町 http://www.town.kikonai.hokkaido.jp/
python ./cmsdetect.py 1 北広島市 https://www.city.kitahiroshima.hokkaido.jp/
python ./cmsdetect.py 1 北見市 http://www.city.kitami.lg.jp/
python ./cmsdetect.py 1 喜茂別町 http://www.town.kimobetsu.hokkaido.jp/
python ./cmsdetect.py 1 京極町 http://www.town-kyogoku.jp/
python ./cmsdetect.py 1 共和町 https://www.town.kyowa.hokkaido.jp/
python ./cmsdetect.py 1 清里町 http://www.town.kiyosato.hokkaido.jp/
python ./cmsdetect.py 1 釧路市 https://www.city.kushiro.lg.jp/
python ./cmsdetect.py 1 釧路町 http://www.town.kushiro.lg.jp/
python ./cmsdetect.py 1 倶知安町 https://www.town.kutchan.hokkaido.jp/
python ./cmsdetect.py 1 栗山町 http://town.kuriyama.hokkaido.jp/
python ./cmsdetect.py 1 黒松内町 http://www.kuromatsunai.com/
python ./cmsdetect.py 1 訓子府町 https://www.town.kunneppu.hokkaido.jp/
python ./cmsdetect.py 1 剣淵町 https://www.town.kembuchi.hokkaido.jp/
python ./cmsdetect.py 1 小清水町 https://www.town.koshimizu.hokkaido.jp/
python ./cmsdetect.py 1 札幌市 http://www.city.sapporo.jp/
python ./cmsdetect.py 1 更別村 http://www.sarabetsu.jp/
python ./cmsdetect.py 1 様似町 http://www.samani.jp/
python ./cmsdetect.py 1 猿払村 https://www.vill.sarufutsu.hokkaido.jp/
python ./cmsdetect.py 1 佐呂間町 http://www.town.saroma.hokkaido.jp/
python ./cmsdetect.py 1 鹿追町 https://www.town.shikaoi.lg.jp/
python ./cmsdetect.py 1 鹿部町 http://www.town.shikabe.lg.jp/
python ./cmsdetect.py 1 標茶町 http://town.shibecha.hokkaido.jp/
python ./cmsdetect.py 1 士別市 http://www.city.shibetsu.lg.jp/
python ./cmsdetect.py 1 標津町 https://www.shibetsutown.jp/
python ./cmsdetect.py 1 士幌町 https://www.shihoro.jp/
python ./cmsdetect.py 1 島牧村 https://www.vill.shimamaki.lg.jp/
python ./cmsdetect.py 1 清水町 http://www.town.shimizu.hokkaido.jp/
python ./cmsdetect.py 1 占冠村 http://www.vill.shimukappu.lg.jp/
python ./cmsdetect.py 1 下川町 https://www.town.shimokawa.hokkaido.jp/
python ./cmsdetect.py 1 積丹町 http://www.town.shakotan.hokkaido.jp/
python ./cmsdetect.py 1 斜里町 http://www.town.shari.hokkaido.jp/
python ./cmsdetect.py 1 初山別村 http://www.vill.shosanbetsu.lg.jp/
python ./cmsdetect.py 1 白老町 http://www.town.shiraoi.hokkaido.jp/
python ./cmsdetect.py 1 白糠町 https://www.town.shiranuka.lg.jp/
python ./cmsdetect.py 1 知内町 http://www.town.shiriuchi.hokkaido.jp/
python ./cmsdetect.py 1 新篠津村 https://www.vill.shinshinotsu.hokkaido.jp/
python ./cmsdetect.py 1 新得町 https://www.shintoku-town.jp/
python ./cmsdetect.py 1 新十津川町 http://www.town.shintotsukawa.lg.jp/
python ./cmsdetect.py 1 新ひだか町 https://www.shinhidaka-hokkaido.jp/
python ./cmsdetect.py 1 寿都町 http://www.town.suttu.lg.jp/
python ./cmsdetect.py 1 砂川市 http://www.city.sunagawa.hokkaido.jp/
python ./cmsdetect.py 1 せなた町 https://www.town.setana.lg.jp/
python ./cmsdetect.py 1 壮瞥町 https://www.town.sobetsu.lg.jp/
python ./cmsdetect.py 1 大樹町 https://www.town.taiki.hokkaido.jp/
python ./cmsdetect.py 1 鷹栖町 http://www.town.takasu.hokkaido.jp/
python ./cmsdetect.py 1 滝川市 https://www.city.takikawa.hokkaido.jp/
python ./cmsdetect.py 1 滝上町 http://town.takinoue.hokkaido.jp/
python ./cmsdetect.py 1 伊達市 https://www.city.date.hokkaido.jp/
python ./cmsdetect.py 1 秩父別町 https://www.town.chippubetsu.hokkaido.jp/
python ./cmsdetect.py 1 千歳市 http://www.city.chitose.lg.jp/
python ./cmsdetect.py 1 月形町 http://www.town.tsukigata.hokkaido.jp/
python ./cmsdetect.py 1 津別町 http://www.town.tsubetsu.hokkaido.jp/
python ./cmsdetect.py 1 鶴居村 https://www.vill.tsurui.lg.jp/
python ./cmsdetect.py 1 天塩町 http://www.teshiotown.hokkaido.jp/
python ./cmsdetect.py 1 弟子屈町 https://www.town.teshikaga.hokkaido.jp/
python ./cmsdetect.py 1 当別町 https://www.town.tobetsu.hokkaido.jp/
python ./cmsdetect.py 1 当麻町 http://town.tohma.hokkaido.jp/
python ./cmsdetect.py 1 洞爺湖町 http://www.town.toyako.hokkaido.jp/
python ./cmsdetect.py 1 苫小牧市 http://www.city.tomakomai.hokkaido.jp/
python ./cmsdetect.py 1 苫前町 http://www.town.tomamae.lg.jp/
python ./cmsdetect.py 1 泊村 http://www.vill.tomari.hokkaido.jp/
python ./cmsdetect.py 1 豊浦町 http://www.town.toyoura.hokkaido.jp/
python ./cmsdetect.py 1 豊頃町 http://www.toyokoro.jp/
python ./cmsdetect.py 1 豊富町 https://www.town.toyotomi.hokkaido.jp/
python ./cmsdetect.py 1 奈井江町 http://www.town.naie.hokkaido.jp/
python ./cmsdetect.py 1 中川町 http://www.town.nakagawa.hokkaido.jp/
python ./cmsdetect.py 1 中札内村 https://www.vill.nakasatsunai.hokkaido.jp/
python ./cmsdetect.py 1 中標津町 http://www.nakashibetsu.jp/
python ./cmsdetect.py 1 中頓別町 https://www.town.nakatombetsu.hokkaido.jp/
python ./cmsdetect.py 1 長沼町 https://www.maoi-net.jp/
python ./cmsdetect.py 1 中富良野町 http://www.town.nakafurano.lg.jp/
python ./cmsdetect.py 1 七飯町 https://www.town.nanae.hokkaido.jp/
python ./cmsdetect.py 1 名寄市 http://www.city.nayoro.lg.jp/
python ./cmsdetect.py 1 南幌町 http://www.town.nanporo.hokkaido.jp/
python ./cmsdetect.py 1 新冠町 https://www.niikappu.jp/
python ./cmsdetect.py 1 仁木町 http://www.town.niki.hokkaido.jp/
python ./cmsdetect.py 1 西興部村 https://www.vill.nishiokoppe.lg.jp/
python ./cmsdetect.py 1 ニセコ町 https://www.town.niseko.lg.jp/
python ./cmsdetect.py 1 沼田町 https://www.town.numata.hokkaido.jp/
python ./cmsdetect.py 1 根室市 https://www.city.nemuro.hokkaido.jp/
python ./cmsdetect.py 1 登別市 https://www.city.noboribetsu.lg.jp/
python ./cmsdetect.py 1 函館市 https://www.city.hakodate.hokkaido.jp/
python ./cmsdetect.py 1 羽幌町 http://www.town.haboro.hokkaido.jp/
python ./cmsdetect.py 1 浜頓別町 http://www.town.hamatonbetsu.hokkaido.jp/
python ./cmsdetect.py 1 浜中町 https://www.townhamanaka.jp/
python ./cmsdetect.py 1 美瑛町 https://town.biei.hokkaido.jp/
python ./cmsdetect.py 1 東神楽町 https://www.town.higashikagura.lg.jp/
python ./cmsdetect.py 1 東川町 https://town.higashikawa.hokkaido.jp/
python ./cmsdetect.py 1 日高町 http://www.town.hidaka.hokkaido.jp/
python ./cmsdetect.py 1 比布町 http://www.town.pippu.hokkaido.jp/
python ./cmsdetect.py 1 美唄市 http://www.city.bibai.hokkaido.jp/
python ./cmsdetect.py 1 美深町 http://www.town.bifuka.hokkaido.jp/
python ./cmsdetect.py 1 美幌町 http://www.town.bihoro.hokkaido.jp/
python ./cmsdetect.py 1 平取町 http://www.town.biratori.hokkaido.jp/
python ./cmsdetect.py 1 広尾町 https://www.town.hiroo.lg.jp/
python ./cmsdetect.py 1 深川市 https://www.city.fukagawa.lg.jp/
python ./cmsdetect.py 1 福島町 http://www.town.fukushima.hokkaido.jp/
python ./cmsdetect.py 1 富良野市 http://www.city.furano.hokkaido.jp/
python ./cmsdetect.py 1 古平町 http://www.town.furubira.lg.jp/
python ./cmsdetect.py 1 別海町 https://betsukai.jp/
python ./cmsdetect.py 1 北斗市 https://www.city.hokuto.hokkaido.jp/
python ./cmsdetect.py 1 北竜町 http://www.town.hokuryu.hokkaido.jp/
python ./cmsdetect.py 1 幌加内町 http://www.town.horokanai.hokkaido.jp/
python ./cmsdetect.py 1 幌延町 https://www.town.horonobe.lg.jp/
python ./cmsdetect.py 1 本別町 http://www.town.honbetsu.hokkaido.jp/
python ./cmsdetect.py 1 幕別町 https://www.town.makubetsu.lg.jp/
python ./cmsdetect.py 1 増毛町 https://www.town.mashike.hokkaido.jp/
python ./cmsdetect.py 1 真狩村 https://www.vill.makkari.lg.jp/
python ./cmsdetect.py 1 松前町 http://www.town.matsumae.hokkaido.jp/
python ./cmsdetect.py 1 三笠市 https://www.city.mikasa.hokkaido.jp/
python ./cmsdetect.py 1 南富良野町 https://www.town.minamifurano.hokkaido.jp/
python ./cmsdetect.py 1 むかわ町 http://www.town.mukawa.lg.jp/
python ./cmsdetect.py 1 室蘭市 http://www.city.muroran.lg.jp/
python ./cmsdetect.py 1 芽室町 http://www.town.moseushi.hokkaido.jp/
python ./cmsdetect.py 1 妹背牛町 https://www.town.moseushi.hokkaido.jp/
python ./cmsdetect.py 1 森町 https://www.town.hokkaido-mori.lg.jp/
python ./cmsdetect.py 1 紋別市 https://mombetsu.jp/
python ./cmsdetect.py 1 八雲町 https://www.town.yakumo.lg.jp/
python ./cmsdetect.py 1 夕張市 https://www.city.yubari.lg.jp/
python ./cmsdetect.py 1 湧別町 https://www.town.yubetsu.lg.jp/
python ./cmsdetect.py 1 由仁町 http://www.town.yuni.lg.jp/
python ./cmsdetect.py 1 余市町 http://www.town.yoichi.hokkaido.jp/
python ./cmsdetect.py 1 羅臼町 https://www.rausu-town.jp/
python ./cmsdetect.py 1 蘭越町 http://www.town.rankoshi.hokkaido.jp/
python ./cmsdetect.py 1 陸別町 https://www.rikubetsu.jp/
python ./cmsdetect.py 1 利尻町 http://www.town.rishiri.hokkaido.jp/
python ./cmsdetect.py 1 利尻富士町 https://www.town.rishirifuji.hokkaido.jp/
python ./cmsdetect.py 1 留寿都村 http://www.vill.rusutsu.lg.jp/
python ./cmsdetect.py 1 留萌市 https://www.e-rumoi.jp/
python ./cmsdetect.py 1 礼文町 http://www.town.rebun.hokkaido.jp/
python ./cmsdetect.py 1 稚内市 https://www.city.wakkanai.hokkaido.jp/
python ./cmsdetect.py 1 和寒町 https://www.town.wassamu.hokkaido.jp/
