python ./cmsdetect.py 10 群馬県 https://www.pref.gunma.jp/
python ./cmsdetect.py 10 前橋市 https://www.city.maebashi.gunma.jp/
python ./cmsdetect.py 10 高崎市 http://www.city.takasaki.gunma.jp/
python ./cmsdetect.py 10 桐生市 http://www.city.kiryu.lg.jp/
python ./cmsdetect.py 10 伊勢崎市 http://www.city.isesaki.lg.jp/
python ./cmsdetect.py 10 太田市 https://www.city.ota.gunma.jp/
python ./cmsdetect.py 10 沼田市 http://www.city.numata.gunma.jp/
python ./cmsdetect.py 10 館林市 https://www.city.tatebayashi.gunma.jp/
python ./cmsdetect.py 10 渋川市 https://www.city.shibukawa.lg.jp/
python ./cmsdetect.py 10 藤岡市 https://www.city.fujioka.gunma.jp
python ./cmsdetect.py 10 富岡市 https://www.city.tomioka.lg.jp/
python ./cmsdetect.py 10 安中市 https://www.city.annaka.lg.jp/
python ./cmsdetect.py 10 みどり市 https://www.city.midori.gunma.jp/www/
python ./cmsdetect.py 10 榛東村 http://www.vill.shinto.gunma.jp/
python ./cmsdetect.py 10 吉岡町 http://www.town.yoshioka.gunma.jp/
python ./cmsdetect.py 10 上野村 http://www.uenomura.jp/
python ./cmsdetect.py 10 神流町 http://www.town.kanna.gunma.jp/
python ./cmsdetect.py 10 下仁田町 https://www.town.shimonita.lg.jp/
python ./cmsdetect.py 10 南牧村 http://www.nanmoku.ne.jp/
python ./cmsdetect.py 10 甘楽町 http://www.town.kanra.gunma.jp/
python ./cmsdetect.py 10 中之条町 https://www.town.nakanojo.gunma.jp/
python ./cmsdetect.py 10 東吾妻町 http://www.town.higashiagatsuma.gunma.jp/
python ./cmsdetect.py 10 長野原町 https://www.town.naganohara.gunma.jp/
python ./cmsdetect.py 10 嬬恋村 http://www.vill.tsumagoi.gunma.jp/
python ./cmsdetect.py 10 草津町 https://www.town.kusatsu.gunma.jp/
python ./cmsdetect.py 10 高山村 https://vill.takayama.gunma.jp/
python ./cmsdetect.py 10 片品村 http://www.vill.katashina.gunma.jp/
python ./cmsdetect.py 10 川場村 http://www.vill.kawaba.gunma.jp/
python ./cmsdetect.py 10 昭和村 https://www.vill.showa.gunma.jp/
python ./cmsdetect.py 10 みなかみ町 https://www.town.minakami.gunma.jp/
python ./cmsdetect.py 10 玉村町 https://www.town.tamamura.lg.jp/
python ./cmsdetect.py 10 板倉町 http://www.town.itakura.gunma.jp/
python ./cmsdetect.py 10 明和町 https://www.town.meiwa.gunma.jp/
python ./cmsdetect.py 10 千代田町 http://www.town.chiyoda.gunma.jp/
python ./cmsdetect.py 10 大泉町 https://www.town.oizumi.gunma.jp/
python ./cmsdetect.py 10 邑楽町 https://www.town.ora.gunma.jp/
