python ./cmsdetect.py 11 埼玉県 https://www.pref.saitama.lg.jp/
python ./cmsdetect.py 11 上尾市 http://www.city.ageo.lg.jp/
python ./cmsdetect.py 11 朝霞市 https://www.city.asaka.lg.jp/
python ./cmsdetect.py 11 伊奈町 https://www.town.saitama-ina.lg.jp/
python ./cmsdetect.py 11 入間市 http://www.city.iruma.saitama.jp/
python ./cmsdetect.py 11 小鹿野町 https://www.town.ogano.lg.jp/
python ./cmsdetect.py 11 小川町 https://www.town.ogawa.saitama.jp/
python ./cmsdetect.py 11 桶川市 https://www.city.okegawa.lg.jp/
python ./cmsdetect.py 11 越生町 http://www.town.ogose.saitama.jp/
python ./cmsdetect.py 11 春日部市 http://www.city.kasukabe.lg.jp/
python ./cmsdetect.py 11 加須市 https://www.city.kazo.lg.jp/
python ./cmsdetect.py 11 神川町 http://www.town.kamikawa.saitama.jp/
python ./cmsdetect.py 11 上里町 http://www.town.kamisato.saitama.jp/
python ./cmsdetect.py 11 川口市 https://www.city.kawaguchi.lg.jp/
python ./cmsdetect.py 11 川越市 https://www.city.kawagoe.saitama.jp/
python ./cmsdetect.py 11 川島町 http://www.town.kawajima.saitama.jp/
python ./cmsdetect.py 11 北本市 http://www.city.kitamoto.saitama.jp/
python ./cmsdetect.py 11 行田市 http://www.city.gyoda.lg.jp/
python ./cmsdetect.py 11 久喜市 http://www.city.kuki.lg.jp/
python ./cmsdetect.py 11 熊谷市 http://www.city.kumagaya.lg.jp/
python ./cmsdetect.py 11 鴻巣市 http://www.city.kounosu.saitama.jp/
python ./cmsdetect.py 11 越谷市 http://www.city.koshigaya.saitama.jp/
python ./cmsdetect.py 11 さいたま市 https://www.city.saitama.jp/
python ./cmsdetect.py 11 坂戸市 https://www.city.sakado.lg.jp/
python ./cmsdetect.py 11 幸手市 https://www.city.satte.lg.jp/
python ./cmsdetect.py 11 狭山市 http://www.city.sayama.saitama.jp/
python ./cmsdetect.py 11 志木市 http://www.city.shiki.lg.jp/
python ./cmsdetect.py 11 白岡市 http://www.city.shiraoka.lg.jp/
python ./cmsdetect.py 11 杉戸町 http://www.town.sugito.lg.jp/
python ./cmsdetect.py 11 草加市 http://www.city.soka.saitama.jp/
python ./cmsdetect.py 11 秩父市 http://www.city.chichibu.lg.jp/
python ./cmsdetect.py 11 鶴ヶ島市 http://www.city.tsurugashima.lg.jp/
python ./cmsdetect.py 11 ときがわ町 https://www.town.tokigawa.lg.jp/
python ./cmsdetect.py 11 所沢市 http://www.city.tokorozawa.saitama.jp/
python ./cmsdetect.py 11 戸田市 https://www.city.toda.saitama.jp/
python ./cmsdetect.py 11 長瀞町 http://www.town.nagatoro.saitama.jp/
python ./cmsdetect.py 11 滑川町 http://www.town.namegawa.saitama.jp/
python ./cmsdetect.py 11 新座市 https://www.city.niiza.lg.jp/
python ./cmsdetect.py 11 蓮田市 http://www.city.hasuda.saitama.jp/
python ./cmsdetect.py 11 鳩山町 http://www.town.hatoyama.saitama.jp/
python ./cmsdetect.py 11 羽生市 https://www.city.hanyu.lg.jp/
python ./cmsdetect.py 11 飯能市 https://www.city.hanno.lg.jp/
python ./cmsdetect.py 11 東秩父村 https://www.vill.higashichichibu.saitama.jp/
python ./cmsdetect.py 11 東松山市 http://www.city.higashimatsuyama.lg.jp/
python ./cmsdetect.py 11 日高市 https://www.city.hidaka.lg.jp/
python ./cmsdetect.py 11 深谷市 http://www.city.fukaya.saitama.jp/
python ./cmsdetect.py 11 富士見市 https://www.city.fujimi.saitama.jp/
python ./cmsdetect.py 11 ふじみ野市 https://www.city.fujimino.saitama.jp/
python ./cmsdetect.py 11 本庄市 https://www.city.honjo.lg.jp/
python ./cmsdetect.py 11 松伏町 http://www.town.matsubushi.saitama.jp/
python ./cmsdetect.py 11 三郷市 http://www.city.misato.lg.jp/
python ./cmsdetect.py 11 美里町 http://www.town.saitama-misato.lg.jp/
python ./cmsdetect.py 11 皆野町 https://www.town.minano.saitama.jp/
python ./cmsdetect.py 11 宮代町 http://www.town.miyashiro.lg.jp/
python ./cmsdetect.py 11 三芳町 http://www.town.saitama-miyoshi.lg.jp/
python ./cmsdetect.py 11 毛呂山町 http://www.town.moroyama.saitama.jp/
python ./cmsdetect.py 11 八潮市 http://www.city.yashio.lg.jp/
python ./cmsdetect.py 11 横瀬町 https://www.town.yokoze.saitama.jp/
python ./cmsdetect.py 11 吉川市 https://www.city.yoshikawa.saitama.jp/
python ./cmsdetect.py 11 吉見町 http://www.town.yoshimi.saitama.jp/
python ./cmsdetect.py 11 寄居町 https://www.town.yorii.saitama.jp/
python ./cmsdetect.py 11 嵐山町 http://www.town.ranzan.saitama.jp/
python ./cmsdetect.py 11 和光市 http://www.city.wako.lg.jp/
python ./cmsdetect.py 11 蕨市 https://www.city.warabi.saitama.jp/
