python ./cmsdetect.py 13 東京都 https://www.metro.tokyo.lg.jp/
python ./cmsdetect.py 13 千代田区 https://www.city.chiyoda.lg.jp/
python ./cmsdetect.py 13 中央区 https://www.city.chuo.lg.jp/
python ./cmsdetect.py 13 港区 https://www.city.minato.tokyo.jp/
python ./cmsdetect.py 13 新宿区 http://www.city.shinjuku.lg.jp/
python ./cmsdetect.py 13 文京区 https://www.city.bunkyo.lg.jp/
python ./cmsdetect.py 13 台東区 https://www.city.taito.lg.jp/
python ./cmsdetect.py 13 墨田区 https://www.city.sumida.lg.jp/
python ./cmsdetect.py 13 江東区 https://www.city.koto.lg.jp/
python ./cmsdetect.py 13 品川区 https://www.city.shinagawa.tokyo.jp/
python ./cmsdetect.py 13 目黒区 https://www.city.meguro.tokyo.jp/
python ./cmsdetect.py 13 大田区 https://www.city.ota.tokyo.jp/
python ./cmsdetect.py 13 世田谷区 https://www.city.setagaya.lg.jp/
python ./cmsdetect.py 13 渋谷区 https://www.city.shibuya.tokyo.jp/
python ./cmsdetect.py 13 中野区 https://www.city.tokyo-nakano.lg.jp/
python ./cmsdetect.py 13 杉並区 https://www.city.suginami.tokyo.jp/
python ./cmsdetect.py 13 豊島区 http://www.city.toshima.lg.jp
python ./cmsdetect.py 13 北区 https://www.city.kita.tokyo.jp/
python ./cmsdetect.py 13 荒川区 https://www.city.arakawa.tokyo.jp/
python ./cmsdetect.py 13 板橋区 https://www.city.itabashi.tokyo.jp/
python ./cmsdetect.py 13 練馬区 https://www.city.nerima.tokyo.jp/
python ./cmsdetect.py 13 足立区 https://www.city.adachi.tokyo.jp/
python ./cmsdetect.py 13 葛飾区 https://www.city.katsushika.lg.jp/
python ./cmsdetect.py 13 江戸川区 https://www.city.edogawa.tokyo.jp/
python ./cmsdetect.py 13 八王子市 https://www.city.hachioji.tokyo.jp/
python ./cmsdetect.py 13 立川市 https://www.city.tachikawa.lg.jp/
python ./cmsdetect.py 13 武蔵野市 https://www.city.musashino.lg.jp/
python ./cmsdetect.py 13 三鷹市 https://www.city.mitaka.lg.jp/
python ./cmsdetect.py 13 府中市 https://www.city.fuchu.tokyo.jp/
python ./cmsdetect.py 13 昭島市 https://www.city.akishima.lg.jp/
python ./cmsdetect.py 13 調布市 https://www.city.chofu.tokyo.jp/
python ./cmsdetect.py 13 町田市 https://www.city.machida.tokyo.jp/
python ./cmsdetect.py 13 小金井市 https://www.city.koganei.lg.jp/
python ./cmsdetect.py 13 日野市 https://www.city.hino.lg.jp/
python ./cmsdetect.py 13 国分寺市 https://www.city.kokubunji.tokyo.jp/
python ./cmsdetect.py 13 国立市 https://www.city.kunitachi.tokyo.jp/
python ./cmsdetect.py 13 狛江市 https://www.city.komae.tokyo.jp/
python ./cmsdetect.py 13 東大和市 https://www.city.higashiyamato.lg.jp/
python ./cmsdetect.py 13 武蔵村山市 https://www.city.musashimurayama.lg.jp/
python ./cmsdetect.py 13 多摩市 https://www.city.tama.lg.jp/
python ./cmsdetect.py 13 稲城市 https://www.city.inagi.tokyo.jp/
python ./cmsdetect.py 13 小平市 https://www.city.kodaira.tokyo.jp/
python ./cmsdetect.py 13 東村山市 https://www.city.higashimurayama.tokyo.jp/
python ./cmsdetect.py 13 西東京市 https://www.city.nishitokyo.lg.jp/
python ./cmsdetect.py 13 清瀬市 https://www.city.kiyose.lg.jp/
python ./cmsdetect.py 13 東久留米市 https://www.city.higashikurume.lg.jp/
python ./cmsdetect.py 13 青梅市 https://www.city.ome.tokyo.jp/
python ./cmsdetect.py 13 福生市 https://www.city.fussa.tokyo.jp/
python ./cmsdetect.py 13 羽村市 https://www.city.hamura.tokyo.jp/
python ./cmsdetect.py 13 あきる野市 https://www.city.akiruno.tokyo.jp/
python ./cmsdetect.py 13 瑞穂町 https://www.town.mizuho.tokyo.jp/
python ./cmsdetect.py 13 日の出町 https://www.town.hinode.tokyo.jp/
python ./cmsdetect.py 13 檜原村 https://www.vill.hinohara.tokyo.jp/
python ./cmsdetect.py 13 奥多摩町 https://www.town.okutama.tokyo.jp/
python ./cmsdetect.py 13 大島町 https://www.town.oshima.tokyo.jp/
python ./cmsdetect.py 13 八丈町 https://www.town.hachijo.tokyo.jp/
python ./cmsdetect.py 13 利島村 http://www.toshimamura.org/
python ./cmsdetect.py 13 新島村 http://www.niijima.com/
python ./cmsdetect.py 13 神津島村 https://vill.kouzushima.tokyo.jp/
python ./cmsdetect.py 13 三宅村 https://www.vill.miyake.tokyo.jp/
python ./cmsdetect.py 13 御蔵島村 http://www.mikurasima.jp/
python ./cmsdetect.py 13 青ヶ島村 https://www.vill.aogashima.tokyo.jp/
python ./cmsdetect.py 13 小笠原村 https://www.vill.ogasawara.tokyo.jp/
