python ./cmsdetect.py 15 新潟県 https://www.pref.niigata.lg.jp/
python ./cmsdetect.py 15 阿賀野市 https://www.city.agano.niigata.jp/
python ./cmsdetect.py 15 阿賀町 http://www.town.aga.niigata.jp/
python ./cmsdetect.py 15 粟島浦村 http://www.vill.awashimaura.lg.jp/
python ./cmsdetect.py 15 出雲崎町 http://www.town.izumozaki.niigata.jp/
python ./cmsdetect.py 15 糸魚川市 https://www.city.itoigawa.lg.jp/
python ./cmsdetect.py 15 柏崎市 https://www.city.kashiwazaki.lg.jp/
python ./cmsdetect.py 15 刈羽村 http://www.vill.kariwa.niigata.jp/
python ./cmsdetect.py 15 加茂市 http://www.city.kamo.niigata.jp/
python ./cmsdetect.py 15 五泉市 http://www.city.gosen.niigata.jp/
python ./cmsdetect.py 15 魚沼市 https://www.city.uonuma.niigata.jp/
python ./cmsdetect.py 15 小千谷市 https://www.city.ojiya.niigata.jp/
python ./cmsdetect.py 15 佐渡市 http://www.city.sado.niigata.jp/
python ./cmsdetect.py 15 三条市 https://www.city.sanjo.niigata.jp/
python ./cmsdetect.py 15 新発田市 https://www.city.shibata.lg.jp/
python ./cmsdetect.py 15 上越市 https://www.city.joetsu.niigata.jp/
python ./cmsdetect.py 15 聖籠町 http://www.town.seiro.niigata.jp/
python ./cmsdetect.py 15 胎内市 http://www.city.tainai.niigata.jp/
python ./cmsdetect.py 15 田上町 http://www.town.tagami.niigata.jp/
python ./cmsdetect.py 15 津南町 https://www.town.tsunan.niigata.jp/
python ./cmsdetect.py 15 燕市 http://www.city.tsubame.niigata.jp/
python ./cmsdetect.py 15 十日町市 http://www.city.tokamachi.lg.jp/
python ./cmsdetect.py 15 関川村 http://www.vill.sekikawa.niigata.jp/
python ./cmsdetect.py 15 長岡市 https://www.city.nagaoka.niigata.jp/
python ./cmsdetect.py 15 新潟市 https://www.city.niigata.lg.jp/
python ./cmsdetect.py 15 見附市 http://www.city.mitsuke.niigata.jp/
python ./cmsdetect.py 15 南魚沼市 http://www.city.minamiuonuma.niigata.jp/
python ./cmsdetect.py 15 妙高市 https://www.city.myoko.niigata.jp/
python ./cmsdetect.py 15 村上市 https://www.city.murakami.lg.jp/
python ./cmsdetect.py 15 弥彦村 http://www.vill.yahiko.niigata.jp/
python ./cmsdetect.py 15 湯沢町 https://www.town.yuzawa.lg.jp/
