python ./cmsdetect.py 16 富山県 http://www.pref.toyama.jp/
python ./cmsdetect.py 16 富山市 http://www.city.toyama.toyama.jp/
python ./cmsdetect.py 16 高岡市 https://www.city.takaoka.toyama.jp/
python ./cmsdetect.py 16 魚津市 https://www.city.uozu.toyama.jp/
python ./cmsdetect.py 16 氷見市 https://www.city.himi.toyama.jp/
python ./cmsdetect.py 16 滑川市 https://www.city.namerikawa.toyama.jp/
python ./cmsdetect.py 16 黒部市 https://www.city.kurobe.toyama.jp/
python ./cmsdetect.py 16 砺波市 https://www.city.tonami.toyama.jp/
python ./cmsdetect.py 16 小矢部市 http://www.city.oyabe.toyama.jp/
python ./cmsdetect.py 16 南砺市 https://www.city.nanto.toyama.jp/
python ./cmsdetect.py 16 射水市 https://www.city.imizu.toyama.jp/
python ./cmsdetect.py 16 舟橋村 http://www.vill.funahashi.toyama.jp/wp/
python ./cmsdetect.py 16 上市町 https://www.town.kamiichi.toyama.jp/
python ./cmsdetect.py 16 立山町 https://www.town.tateyama.toyama.jp/
python ./cmsdetect.py 16 入善町 https://www.town.nyuzen.toyama.jp/
python ./cmsdetect.py 16 朝日町 http://www.town.asahi.toyama.jp/
