python ./cmsdetect.py 17 石川県 https://www.pref.ishikawa.lg.jp/
python ./cmsdetect.py 17 金沢市 https://www4.city.kanazawa.lg.jp/
python ./cmsdetect.py 17 七尾市 http://www.city.nanao.lg.jp/
python ./cmsdetect.py 17 小松市 https://www.city.komatsu.lg.jp/
python ./cmsdetect.py 17 輪島市 https://www.city.wajima.ishikawa.jp/
python ./cmsdetect.py 17 珠洲市 http://www.city.suzu.ishikawa.jp/
python ./cmsdetect.py 17 加賀市 https://www.city.kaga.ishikawa.jp/
python ./cmsdetect.py 17 羽咋市 https://www.city.hakui.lg.jp/
python ./cmsdetect.py 17 かほく市 http://www.city.kahoku.ishikawa.jp/www/
python ./cmsdetect.py 17 白山市 https://www.city.hakusan.lg.jp/
python ./cmsdetect.py 17 能美市 https://www.city.nomi.ishikawa.jp/www/
python ./cmsdetect.py 17 野々市市 https://www.city.nonoichi.lg.jp/
python ./cmsdetect.py 17 川北町 http://www.town.kawakita.ishikawa.jp/
python ./cmsdetect.py 17 津幡町 http://www.town.tsubata.lg.jp/
python ./cmsdetect.py 17 内灘町 http://www.town.uchinada.lg.jp/webapps/www/
python ./cmsdetect.py 17 志賀町 https://www.town.shika.lg.jp/index.html
python ./cmsdetect.py 17 宝達志水町 http://www.hodatsushimizu.jp/kurashi/
python ./cmsdetect.py 17 中能登町 http://www.town.nakanoto.ishikawa.jp/
python ./cmsdetect.py 17 穴水町 http://www.town.anamizu.ishikawa.jp/
python ./cmsdetect.py 17 能登町 http://www.town.noto.lg.jp/www/
