python ./cmsdetect.py 18 福井県 https://www.pref.fukui.lg.jp/
python ./cmsdetect.py 18 あわら市 http://www.city.awara.lg.jp/
python ./cmsdetect.py 18 おおい町 https://www.town.ohi.fukui.jp/
python ./cmsdetect.py 18 越前市 http://www.city.echizen.lg.jp/
python ./cmsdetect.py 18 永平寺町 https://www.town.eiheiji.lg.jp/
python ./cmsdetect.py 18 池田町 https://www.town.ikeda.fukui.jp/
python ./cmsdetect.py 18 坂井市 https://www.city.fukui-sakai.lg.jp/
python ./cmsdetect.py 18 鯖江市 https://www.city.sabae.fukui.jp/
python ./cmsdetect.py 18 美浜町 http://www.town.mihama.fukui.jp/
python ./cmsdetect.py 18 若狭町 http://www.town.fukui-wakasa.lg.jp/
python ./cmsdetect.py 18 勝山市 https://www.city.katsuyama.fukui.jp/
python ./cmsdetect.py 18 小浜市 http://www1.city.obama.fukui.jp/
python ./cmsdetect.py 18 高浜町 http://www.town.takahama.fukui.jp/
python ./cmsdetect.py 18 大野市 https://www.city.ono.fukui.jp/
python ./cmsdetect.py 18 越前町 https://www.town.echizen.fukui.jp/
python ./cmsdetect.py 18 敦賀市 https://www.city.tsuruga.lg.jp/
python ./cmsdetect.py 18 南越前町 http://www.town.minamiechizen.lg.jp/
python ./cmsdetect.py 18 福井市 https://www.city.fukui.lg.jp/
