python ./cmsdetect.py 19 山梨県 https://www.pref.yamanashi.jp/
python ./cmsdetect.py 19 甲府市 https://www.city.kofu.yamanashi.jp/
python ./cmsdetect.py 19 富士吉田市 http://www.city.fujiyoshida.yamanashi.jp/
python ./cmsdetect.py 19 都留市 https://www.city.tsuru.yamanashi.jp/
python ./cmsdetect.py 19 山梨市 https://www.city.yamanashi.yamanashi.jp/
python ./cmsdetect.py 19 大月市 http://www.city.otsuki.yamanashi.jp/
python ./cmsdetect.py 19 韮崎市 https://www.city.nirasaki.lg.jp/
python ./cmsdetect.py 19 南アルプス市 https://www.city.minami-alps.yamanashi.jp/
python ./cmsdetect.py 19 北杜市 https://www.city.hokuto.yamanashi.jp/
python ./cmsdetect.py 19 甲斐市 https://www.city.kai.yamanashi.jp/
python ./cmsdetect.py 19 笛吹市 http://www.city.fuefuki.yamanashi.jp/
python ./cmsdetect.py 19 上野原市 https://www.city.uenohara.yamanashi.jp/
python ./cmsdetect.py 19 甲州市 https://www.city.koshu.yamanashi.jp/
python ./cmsdetect.py 19 中央市 https://www.city.chuo.yamanashi.jp/index.html
python ./cmsdetect.py 19 市川三郷町 http://www.town.ichikawamisato.yamanashi.jp/
python ./cmsdetect.py 19 早川町 https://www.town.hayakawa.yamanashi.jp/
python ./cmsdetect.py 19 身延町 https://www.town.minobu.lg.jp/
python ./cmsdetect.py 19 南部町 https://www.town.nanbu.yamanashi.jp/
python ./cmsdetect.py 19 富士川町 https://www.town.fujikawa.yamanashi.jp/
python ./cmsdetect.py 19 昭和町 https://www.town.showa.yamanashi.jp/
python ./cmsdetect.py 19 道志村 http://www.vill.doshi.lg.jp/
python ./cmsdetect.py 19 西桂町 http://www.town.nishikatsura.yamanashi.jp/
python ./cmsdetect.py 19 忍野村 http://www.vill.oshino.yamanashi.jp/
python ./cmsdetect.py 19 山中湖村 https://www.vill.yamanakako.lg.jp/
python ./cmsdetect.py 19 鳴沢村 https://www.vill.narusawa.yamanashi.jp/
python ./cmsdetect.py 19 富士河口湖町 http://www.town.fujikawaguchiko.yamanashi.jp/
python ./cmsdetect.py 19 小菅村 http://www.vill.kosuge.yamanashi.jp/
python ./cmsdetect.py 19 丹波山村 http://www.vill.tabayama.yamanashi.jp/
