python ./cmsdetect.py 2 青森県 https://www.pref.aomori.lg.jp/
python ./cmsdetect.py 2 青森市 http://www.city.aomori.aomori.jp/
python ./cmsdetect.py 2 平内町 http://www.town.hiranai.aomori.jp/
python ./cmsdetect.py 2 今別町 https://www.town.imabetsu.lg.jp/
python ./cmsdetect.py 2 蓬田村 http://www.vill.yomogita.lg.jp/
python ./cmsdetect.py 2 外ヶ浜町 http://www.town.sotogahama.lg.jp/
python ./cmsdetect.py 2 弘前市 http://www.city.hirosaki.aomori.jp/
python ./cmsdetect.py 2 黒石市 http://www.city.kuroishi.aomori.jp/
python ./cmsdetect.py 2 平川市 https://www.city.hirakawa.lg.jp/
python ./cmsdetect.py 2 西目屋村 http://www.nishimeya.jp/
python ./cmsdetect.py 2 藤崎町 http://www.town.fujisaki.lg.jp/
python ./cmsdetect.py 2 大鰐町 http://www.town.owani.lg.jp/
python ./cmsdetect.py 2 田舎館村 http://www.vill.inakadate.lg.jp/
python ./cmsdetect.py 2 五所川原市 http://www.city.goshogawara.lg.jp/
python ./cmsdetect.py 2 つがる市 http://www.city.tsugaru.aomori.jp/
python ./cmsdetect.py 2 鰺ヶ沢町 http://www.town.ajigasawa.lg.jp/wordpress/
python ./cmsdetect.py 2 深浦町 https://www.town.fukaura.lg.jp/
python ./cmsdetect.py 2 板柳町 https://www.town.itayanagi.aomori.jp/
python ./cmsdetect.py 2 鶴田町 http://www.town.tsuruta.lg.jp/
python ./cmsdetect.py 2 中泊町 http://www.town.nakadomari.lg.jp/
python ./cmsdetect.py 2 十和田市 http://www.city.towada.lg.jp/
python ./cmsdetect.py 2 三沢市 http://www.city.misawa.lg.jp/
python ./cmsdetect.py 2 野辺地町 http://www.town.noheji.aomori.jp/
python ./cmsdetect.py 2 七戸町 http://www.town.shichinohe.lg.jp/
python ./cmsdetect.py 2 六戸町 http://www.town.rokunohe.aomori.jp/
python ./cmsdetect.py 2 横浜町 http://www.town.yokohama.lg.jp/
python ./cmsdetect.py 2 東北町 http://www.town.tohoku.lg.jp/
python ./cmsdetect.py 2 六ヶ所村 http://www.rokkasho.jp/
python ./cmsdetect.py 2 おいらせ町 https://www.town.oirase.aomori.jp/
python ./cmsdetect.py 2 むつ市 http://www.city.mutsu.lg.jp/
python ./cmsdetect.py 2 大間町 https://www.town.ooma.lg.jp/
python ./cmsdetect.py 2 東通村 http://www.vill.higashidoori.lg.jp/
python ./cmsdetect.py 2 風間浦村 https://www.kazamaura.jp/
python ./cmsdetect.py 2 佐井村 http://www.vill.sai.lg.jp/
python ./cmsdetect.py 2 八戸市 https://www.city.hachinohe.aomori.jp/
python ./cmsdetect.py 2 三戸町 http://www.town.sannohe.aomori.jp/
python ./cmsdetect.py 2 五戸町 http://www.town.gonohe.aomori.jp/
python ./cmsdetect.py 2 田子町 http://www.town.takko.lg.jp/
python ./cmsdetect.py 2 南部町 http://www.town.aomori-nanbu.lg.jp/
python ./cmsdetect.py 2 階上町 https://www.town.hashikami.lg.jp/
python ./cmsdetect.py 2 新郷村 http://www.vill.shingo.aomori.jp/
