python ./cmsdetect.py 20 長野県 https://www.pref.nagano.lg.jp/
python ./cmsdetect.py 20 阿智村 https://www.vill.achi.lg.jp/
python ./cmsdetect.py 20 阿南町 http://www.town.anan.nagano.jp/
python ./cmsdetect.py 20 安曇野市 http://www.city.azumino.nagano.jp/
python ./cmsdetect.py 20 伊那市 http://www.inacity.jp/
python ./cmsdetect.py 20 栄村 http://www.vill.sakae.nagano.jp/
python ./cmsdetect.py 20 塩尻市 https://www.city.shiojiri.lg.jp/
python ./cmsdetect.py 20 王滝村 http://www.vill.otaki.nagano.jp/
python ./cmsdetect.py 20 岡谷市 http://www.city.okaya.lg.jp/
python ./cmsdetect.py 20 下諏訪町 https://www.town.shimosuwa.lg.jp/
python ./cmsdetect.py 20 下條村 http://www.vill-shimojo.jp/
python ./cmsdetect.py 20 茅野市 https://www.city.chino.lg.jp/
python ./cmsdetect.py 20 宮田村 https://www.vill.miyada.nagano.jp/
python ./cmsdetect.py 20 駒ヶ根市 https://www.city.komagane.nagano.jp/
python ./cmsdetect.py 20 軽井沢町 http://www.town.karuizawa.lg.jp/
python ./cmsdetect.py 20 原村 https://www.vill.hara.lg.jp/
python ./cmsdetect.py 20 御代田町 https://www.town.miyota.nagano.jp/
python ./cmsdetect.py 20 高山村 http://www.vill.takayama.nagano.jp/
python ./cmsdetect.py 20 高森町 http://www.town.takamori.nagano.jp/
python ./cmsdetect.py 20 根羽村 http://nebamura.jp/
python ./cmsdetect.py 20 佐久市 http://www.city.saku.nagano.jp/
python ./cmsdetect.py 20 佐久穂町 https://www.town.sakuho.nagano.jp/
python ./cmsdetect.py 20 坂城町 http://www.town.sakaki.nagano.jp/
python ./cmsdetect.py 20 山ノ内町 http://www.town.yamanouchi.nagano.jp/
python ./cmsdetect.py 20 山形村 https://www.vill.yamagata.nagano.jp/
python ./cmsdetect.py 20 小海町 http://www.koumi-town.jp/
python ./cmsdetect.py 20 小諸市 https://www.city.komoro.lg.jp/
python ./cmsdetect.py 20 小川村 http://www.vill.ogawa.nagano.jp/wordpress/
python ./cmsdetect.py 20 小谷村 https://www.vill.otari.nagano.jp/www/
python ./cmsdetect.py 20 小布施町 https://www.town.obuse.nagano.jp/
python ./cmsdetect.py 20 松川村 http://www.vill.matsukawa.nagano.jp/
python ./cmsdetect.py 20 松川町 https://www.town.matsukawa.lg.jp/
python ./cmsdetect.py 20 松本市 http://www.city.matsumoto.nagano.jp/
python ./cmsdetect.py 20 上松町 http://www.town.agematsu.nagano.jp/
python ./cmsdetect.py 20 上田市 https://www.city.ueda.nagano.jp/
python ./cmsdetect.py 20 信濃町 https://www.town.shinano.lg.jp/
python ./cmsdetect.py 20 諏訪市 http://www.city.suwa.lg.jp/
python ./cmsdetect.py 20 須坂市 https://www.city.suzaka.nagano.jp/
python ./cmsdetect.py 20 生坂村 http://www.village.ikusaka.nagano.jp/
python ./cmsdetect.py 20 青木村 http://www.vill.aoki.nagano.jp/
python ./cmsdetect.py 20 千曲市 https://www.city.chikuma.lg.jp/
python ./cmsdetect.py 20 川上村 http://www.vill.kawakami.nagano.jp/www/
python ./cmsdetect.py 20 泰阜村 http://www.vill.yasuoka.nagano.jp/
python ./cmsdetect.py 20 大桑村 http://www.vill.ookuwa.nagano.jp/
python ./cmsdetect.py 20 大鹿村 http://www.vill.ooshika.nagano.jp/
python ./cmsdetect.py 20 大町市 http://www.city.omachi.nagano.jp/
python ./cmsdetect.py 20 辰野町 http://www.town.tatsuno.nagano.jp/
python ./cmsdetect.py 20 池田町 http://www.ikedamachi.net/
python ./cmsdetect.py 20 筑北村 http://www.vill.chikuhoku.lg.jp/
python ./cmsdetect.py 20 中川村 https://www.vill.nakagawa.nagano.jp/
python ./cmsdetect.py 20 中野市 https://www.city.nakano.nagano.jp/
python ./cmsdetect.py 20 朝日村 https://www.vill.asahi.nagano.jp/
python ./cmsdetect.py 20 長野市 https://www.city.nagano.nagano.jp/
python ./cmsdetect.py 20 長和町 http://town.nagawa.nagano.jp/
python ./cmsdetect.py 20 天龍村 http://www.vill-tenryu.jp/
python ./cmsdetect.py 20 東御市 https://www.city.tomi.nagano.jp/
python ./cmsdetect.py 20 南相木村 http://www.minamiaiki.jp/
python ./cmsdetect.py 20 南牧村 https://www.minamimakimura.jp/
python ./cmsdetect.py 20 南箕輪村 https://www.vill.minamiminowa.lg.jp/
python ./cmsdetect.py 20 南木曽町 http://www.town.nagiso.nagano.jp/
python ./cmsdetect.py 20 売木村 http://www.urugi.jp/
python ./cmsdetect.py 20 白馬村 https://www.vill.hakuba.nagano.jp/
python ./cmsdetect.py 20 飯綱町 https://www.town.iizuna.nagano.jp/
python ./cmsdetect.py 20 飯山市 https://www.city.iiyama.nagano.jp/
python ./cmsdetect.py 20 飯田市 https://www.city.iida.lg.jp/
python ./cmsdetect.py 20 飯島町 https://www.town.iijima.lg.jp/
python ./cmsdetect.py 20 富士見町 http://www.town.fujimi.lg.jp/
python ./cmsdetect.py 20 平谷村 http://hirayamura.jp/
python ./cmsdetect.py 20 豊丘村 https://www.vill.nagano-toyooka.lg.jp/
python ./cmsdetect.py 20 北相木村 http://vill.kitaaiki.nagano.jp/
python ./cmsdetect.py 20 麻績村 http://www.vill.omi.nagano.jp/
python ./cmsdetect.py 20 箕輪町 http://www.town.minowa.lg.jp/
python ./cmsdetect.py 20 木曽町 https://www.town-kiso.com/
python ./cmsdetect.py 20 木祖村 http://www.vill.kiso.nagano.jp/
python ./cmsdetect.py 20 木島平村 http://www.vill.kijimadaira.lg.jp/
python ./cmsdetect.py 20 野沢温泉村 http://www.vill.nozawaonsen.nagano.jp/
python ./cmsdetect.py 20 立科町 http://www.town.tateshina.nagano.jp/
python ./cmsdetect.py 20 喬木村 http://www.vill.takagi.nagano.jp/
