python ./cmsdetect.py 21 岐阜県 https://www.pref.gifu.lg.jp/
python ./cmsdetect.py 21 岐阜市 https://www.city.gifu.lg.jp/
python ./cmsdetect.py 21 大垣市 https://www.city.ogaki.lg.jp/
python ./cmsdetect.py 21 高山市 https://www.city.takayama.lg.jp/
python ./cmsdetect.py 21 多治見市 https://www.city.tajimi.lg.jp/
python ./cmsdetect.py 21 関市 https://www.city.seki.lg.jp/
python ./cmsdetect.py 21 中津川市 http://www.city.nakatsugawa.gifu.jp/
python ./cmsdetect.py 21 美濃市 http://www.city.mino.gifu.jp/
python ./cmsdetect.py 21 瑞浪市 https://www.city.mizunami.lg.jp/
python ./cmsdetect.py 21 羽島市 https://www.city.hashima.lg.jp/
python ./cmsdetect.py 21 恵那市 https://www.city.ena.lg.jp/
python ./cmsdetect.py 21 美濃加茂市 https://www.city.minokamo.gifu.jp/shimin/
python ./cmsdetect.py 21 土岐市 https://www.city.toki.lg.jp/
python ./cmsdetect.py 21 各務原市 http://www.city.kakamigahara.lg.jp/
python ./cmsdetect.py 21 可児市 https://www.city.kani.lg.jp/
python ./cmsdetect.py 21 山県市 https://www.city.yamagata.gifu.jp/
python ./cmsdetect.py 21 瑞穂市 http://www.city.mizuho.lg.jp/
python ./cmsdetect.py 21 飛騨市 http://www.city.hida.gifu.jp/
python ./cmsdetect.py 21 本巣市 https://www.city.motosu.lg.jp/
python ./cmsdetect.py 21 郡上市 https://www.city.gujo.gifu.jp/
python ./cmsdetect.py 21 下呂市 http://www.city.gero.lg.jp/
python ./cmsdetect.py 21 海津市 https://www.city.kaizu.lg.jp/
python ./cmsdetect.py 21 岐南町 https://www.town.ginan.lg.jp/
python ./cmsdetect.py 21 笠松町 https://www.town.kasamatsu.gifu.jp/
python ./cmsdetect.py 21 養老町 http://www.town.yoro.gifu.jp/
python ./cmsdetect.py 21 垂井町 http://www.town.tarui.lg.jp/
python ./cmsdetect.py 21 関ケ原町‎ http://www.town.sekigahara.gifu.jp/
python ./cmsdetect.py 21 神戸町 http://www.town.godo.gifu.jp/
python ./cmsdetect.py 21 輪之内町 http://town.wanouchi.gifu.jp/
python ./cmsdetect.py 21 安八町 http://www.town.anpachi.gifu.jp/
python ./cmsdetect.py 21 揖斐川町 https://www.town.ibigawa.lg.jp/
python ./cmsdetect.py 21 大野町 https://www.town-ono.jp/
python ./cmsdetect.py 21 池田町 https://www.town.gifu-ikeda.lg.jp/
python ./cmsdetect.py 21 北方町 http://www.town.kitagata.gifu.jp/
python ./cmsdetect.py 21 坂祝町 https://www.town.sakahogi.gifu.jp/
python ./cmsdetect.py 21 富加町 http://www.town.tomika.gifu.jp/
python ./cmsdetect.py 21 川辺町 https://www.kawabe-gifu.jp/
python ./cmsdetect.py 21 七宗町 http://www.hichiso.jp/
python ./cmsdetect.py 21 八百津町 https://www.town.yaotsu.lg.jp/
python ./cmsdetect.py 21 白川町 https://www.town.shirakawa.lg.jp/
python ./cmsdetect.py 21 東白川村 https://www.vill.higashishirakawa.gifu.jp/
python ./cmsdetect.py 21 御嵩町 https://www.town.mitake.lg.jp/
python ./cmsdetect.py 21 白川村 http://shirakawa-go.org/
