python ./cmsdetect.py 22 静岡県 http://www.pref.shizuoka.jp/
python ./cmsdetect.py 22 浜松市 https://www.city.hamamatsu.shizuoka.jp/
python ./cmsdetect.py 22 磐田市 https://www.city.iwata.shizuoka.jp/
python ./cmsdetect.py 22 掛川市 https://www.city.kakegawa.shizuoka.jp/
python ./cmsdetect.py 22 袋井市 https://www.city.fukuroi.shizuoka.jp/
python ./cmsdetect.py 22 湖西市 https://www.city.kosai.shizuoka.jp/
python ./cmsdetect.py 22 御前崎市 https://www.city.omaezaki.shizuoka.jp
python ./cmsdetect.py 22 菊川市 http://www.city.kikugawa.shizuoka.jp/
python ./cmsdetect.py 22 森町 https://www.town.morimachi.shizuoka.jp/
python ./cmsdetect.py 22 静岡市 https://www.city.shizuoka.lg.jp/
python ./cmsdetect.py 22 島田市 https://www.city.shimada.shizuoka.jp/
python ./cmsdetect.py 22 焼津市 http://www.city.yaizu.lg.jp/
python ./cmsdetect.py 22 藤枝市 https://www.city.fujieda.shizuoka.jp/
python ./cmsdetect.py 22 牧之原市 https://www.city.makinohara.shizuoka.jp/
python ./cmsdetect.py 22 吉田町 http://www.town.yoshida.shizuoka.jp/
python ./cmsdetect.py 22 川根本町 http://www.town.kawanehon.shizuoka.jp/
python ./cmsdetect.py 22 沼津市 https://www.city.numazu.shizuoka.jp/
python ./cmsdetect.py 22 熱海市 https://www.city.atami.lg.jp/
python ./cmsdetect.py 22 三島市 http://www.city.mishima.shizuoka.jp/
python ./cmsdetect.py 22 富士宮市 http://www.city.fujinomiya.lg.jp/
python ./cmsdetect.py 22 伊東市 https://www.city.ito.shizuoka.jp/
python ./cmsdetect.py 22 富士市 https://www.city.fuji.shizuoka.jp/
python ./cmsdetect.py 22 御殿場市 https://www.city.gotemba.lg.jp/
python ./cmsdetect.py 22 裾野市 http://www.city.susono.shizuoka.jp/
python ./cmsdetect.py 22 伊豆市 http://www.city.izu.shizuoka.jp/
python ./cmsdetect.py 22 伊豆の国市 https://www.city.izunokuni.shizuoka.jp/
python ./cmsdetect.py 22 函南町 http://www.town.kannami.shizuoka.jp/
python ./cmsdetect.py 22 清水町 http://www.town.shimizu.shizuoka.jp/
python ./cmsdetect.py 22 長泉町 http://www.town.nagaizumi.lg.jp/
python ./cmsdetect.py 22 小山町 http://www.fuji-oyama.jp/
python ./cmsdetect.py 22 下田市 https://www.city.shimoda.shizuoka.jp/
python ./cmsdetect.py 22 東伊豆町 https://www.town.higashiizu.shizuoka.jp/
python ./cmsdetect.py 22 河津町 https://www.town.kawazu.shizuoka.jp/
python ./cmsdetect.py 22 南伊豆町 https://www.town.minamiizu.shizuoka.jp/
python ./cmsdetect.py 22 松崎町 https://www.town.matsuzaki.shizuoka.jp/
python ./cmsdetect.py 22 西伊豆町 http://www.town.nishiizu.shizuoka.jp/
