python ./cmsdetect.py 24 三重県 http://www.pref.mie.lg.jp/
python ./cmsdetect.py 24 桑名市 http://www.city.kuwana.lg.jp/
python ./cmsdetect.py 24 いなべ市 https://www.city.inabe.mie.jp/
python ./cmsdetect.py 24 木曽岬町 https://www.town.kisosaki.lg.jp/
python ./cmsdetect.py 24 東員町 http://www.town.toin.lg.jp/
python ./cmsdetect.py 24 四日市市 https://www.city.yokkaichi.lg.jp/
python ./cmsdetect.py 24 菰野町 http://www2.town.komono.mie.jp/
python ./cmsdetect.py 24 朝日町 http://www2.town.asahi.mie.jp/
python ./cmsdetect.py 24 川越町 http://www.town.kawagoe.mie.jp/
python ./cmsdetect.py 24 鈴鹿市 https://www.city.suzuka.lg.jp/
python ./cmsdetect.py 24 亀山市 https://www.city.kameyama.mie.jp/
python ./cmsdetect.py 24 津市 https://www.info.city.tsu.mie.jp/
python ./cmsdetect.py 24 松阪市 https://www.city.matsusaka.mie.jp/
python ./cmsdetect.py 24 多気町 http://www.town.taki.mie.jp/
python ./cmsdetect.py 24 明和町 https://www.town.meiwa.mie.jp/
python ./cmsdetect.py 24 大台町 http://www.odaitown.jp/
python ./cmsdetect.py 24 伊勢市 https://www.city.ise.mie.jp/
python ./cmsdetect.py 24 鳥羽市 http://www.city.toba.mie.jp/
python ./cmsdetect.py 24 志摩市 http://www.city.shima.mie.jp/
python ./cmsdetect.py 24 玉城町 https://kizuna.town.tamaki.mie.jp/town_site/index/
python ./cmsdetect.py 24 度会町 http://www.town.watarai.lg.jp/
python ./cmsdetect.py 24 大紀町 http://www.town.taiki.mie.jp
python ./cmsdetect.py 24 南伊勢町 https://www.town.minamiise.lg.jp/
python ./cmsdetect.py 24 伊賀市 https://www.city.iga.lg.jp/
python ./cmsdetect.py 24 名張市 http://www.city.nabari.lg.jp/
python ./cmsdetect.py 24 尾鷲市 https://www.city.owase.lg.jp/
python ./cmsdetect.py 24 紀北町 http://www.town.mie-kihoku.lg.jp/
python ./cmsdetect.py 24 熊野市 https://www.city.kumano.lg.jp/
python ./cmsdetect.py 24 御浜町 http://www.town.mihama.mie.jp/
python ./cmsdetect.py 24 紀宝町 https://www.town.kiho.lg.jp/
