python ./cmsdetect.py 25 滋賀県 https://www.pref.shiga.lg.jp/
python ./cmsdetect.py 25 大津市 https://www.city.otsu.lg.jp/
python ./cmsdetect.py 25 草津市 http://www.city.kusatsu.shiga.jp/
python ./cmsdetect.py 25 守山市 http://www.city.moriyama.lg.jp/
python ./cmsdetect.py 25 栗東市 http://www.city.ritto.lg.jp/
python ./cmsdetect.py 25 野洲市 https://www.city.yasu.lg.jp/
python ./cmsdetect.py 25 甲賀市 https://www.city.koka.lg.jp/
python ./cmsdetect.py 25 湖南市 https://www.city.shiga-konan.lg.jp/
python ./cmsdetect.py 25 東近江市 http://www.city.higashiomi.shiga.jp/
python ./cmsdetect.py 25 近江八幡市 https://www.city.omihachiman.lg.jp/
python ./cmsdetect.py 25 日野町 http://www.town.shiga-hino.lg.jp/
python ./cmsdetect.py 25 竜王町 http://www.town.ryuoh.shiga.jp/
python ./cmsdetect.py 25 彦根市 https://www.city.hikone.lg.jp/
python ./cmsdetect.py 25 愛荘町 https://www.town.aisho.shiga.jp/
python ./cmsdetect.py 25 豊郷町 http://www.town.toyosato.shiga.jp/
python ./cmsdetect.py 25 甲良町 http://www.kouratown.jp/
python ./cmsdetect.py 25 多賀町 http://www.town.taga.lg.jp/
python ./cmsdetect.py 25 米原市 https://www.city.maibara.lg.jp/
python ./cmsdetect.py 25 長浜市 https://www.city.nagahama.lg.jp/
python ./cmsdetect.py 25 高島市 http://www.city.takashima.shiga.jp/
