python ./cmsdetect.py 26 京都府 http://www.pref.kyoto.jp/
python ./cmsdetect.py 26 京都市 https://www.city.kyoto.lg.jp/
python ./cmsdetect.py 26 福知山市 https://www.city.fukuchiyama.lg.jp/
python ./cmsdetect.py 26 舞鶴市 https://www.city.maizuru.kyoto.jp/
python ./cmsdetect.py 26 綾部市 http://www.city.ayabe.lg.jp/
python ./cmsdetect.py 26 宇治市 https://www.city.uji.kyoto.jp/
python ./cmsdetect.py 26 宮津市 http://www.city.miyazu.kyoto.jp/
python ./cmsdetect.py 26 亀岡市 http://www.city.kameoka.kyoto.jp/
python ./cmsdetect.py 26 城陽市 https://www.city.joyo.kyoto.jp/
python ./cmsdetect.py 26 向日市 https://www.city.muko.kyoto.jp/
python ./cmsdetect.py 26 長岡京市 http://www.city.nagaokakyo.lg.jp/
python ./cmsdetect.py 26 八幡市 http://www.city.yawata.kyoto.jp/
python ./cmsdetect.py 26 京田辺市 http://www.kyotanabe.jp/
python ./cmsdetect.py 26 京丹後市 http://www.city.kyotango.lg.jp/
python ./cmsdetect.py 26 南丹市 https://www.city.nantan.kyoto.jp/www/
python ./cmsdetect.py 26 木津川市 http://www.city.kizugawa.lg.jp/
python ./cmsdetect.py 26 大山崎町 http://www.town.oyamazaki.kyoto.jp/
python ./cmsdetect.py 26 久御山町 http://www.town.kumiyama.kyoto.jp/
python ./cmsdetect.py 26 井手町 http://www.town.ide.kyoto.jp/
python ./cmsdetect.py 26 宇治田原町 http://www.town.ujitawara.kyoto.jp/
python ./cmsdetect.py 26 笠置町 http://www.town.kasagi.lg.jp/
python ./cmsdetect.py 26 和束町 http://www.town.wazuka.lg.jp/
python ./cmsdetect.py 26 精華町 https://www.town.seika.kyoto.jp/
python ./cmsdetect.py 26 南山城村 http://www.vill.minamiyamashiro.lg.jp/
python ./cmsdetect.py 26 京丹波町 http://www.town.kyotamba.kyoto.jp/
python ./cmsdetect.py 26 伊根町 http://www.town.ine.kyoto.jp/
python ./cmsdetect.py 26 与謝野町 http://www.town-yosano.jp/
