python ./cmsdetect.py 27 大阪府 http://www.pref.osaka.lg.jp/
python ./cmsdetect.py 27 大阪市 https://www.city.osaka.lg.jp/
python ./cmsdetect.py 27 堺市 http://www.city.sakai.lg.jp/
python ./cmsdetect.py 27 能勢町 http://www.town.nose.osaka.jp/
python ./cmsdetect.py 27 豊能町 http://www.town.toyono.osaka.jp/
python ./cmsdetect.py 27 池田市 http://www.city.ikeda.osaka.jp/
python ./cmsdetect.py 27 箕面市 https://www.city.minoh.lg.jp/
python ./cmsdetect.py 27 豊中市 https://www.city.toyonaka.osaka.jp/
python ./cmsdetect.py 27 茨木市 https://www.city.ibaraki.osaka.jp/
python ./cmsdetect.py 27 高槻市 http://www.city.takatsuki.osaka.jp/
python ./cmsdetect.py 27 島本町 http://www.shimamotocho.jp/
python ./cmsdetect.py 27 吹田市 https://www.city.suita.osaka.jp/
python ./cmsdetect.py 27 摂津市 https://www.city.settsu.osaka.jp/
python ./cmsdetect.py 27 枚方市 https://www.city.hirakata.osaka.jp/
python ./cmsdetect.py 27 交野市 https://www.city.katano.osaka.jp/
python ./cmsdetect.py 27 寝屋川市 https://www.city.neyagawa.osaka.jp/
python ./cmsdetect.py 27 守口市 http://www.city.moriguchi.osaka.jp/
python ./cmsdetect.py 27 門真市 https://www.city.kadoma.osaka.jp/
python ./cmsdetect.py 27 四條畷市 https://www.city.shijonawate.lg.jp/
python ./cmsdetect.py 27 大東市 http://www.city.daito.lg.jp/
python ./cmsdetect.py 27 東大阪市 http://www.city.higashiosaka.lg.jp/
python ./cmsdetect.py 27 八尾市 https://www.city.yao.osaka.jp/
python ./cmsdetect.py 27 柏原市 http://www.city.kashiwara.osaka.jp/
python ./cmsdetect.py 27 和泉市 https://www.city.osaka-izumi.lg.jp/
python ./cmsdetect.py 27 高石市 http://www.city.takaishi.lg.jp/
python ./cmsdetect.py 27 泉大津市 https://www.city.izumiotsu.lg.jp/
python ./cmsdetect.py 27 忠岡町 https://www.town.tadaoka.osaka.jp/
python ./cmsdetect.py 27 岸和田市 https://www.city.kishiwada.osaka.jp/
python ./cmsdetect.py 27 貝塚市 https://www.city.kaizuka.lg.jp/
python ./cmsdetect.py 27 熊取町 https://www.town.kumatori.lg.jp/
python ./cmsdetect.py 27 泉佐野市 http://www.city.izumisano.lg.jp/
python ./cmsdetect.py 27 田尻町 http://www.town.tajiri.osaka.jp/
python ./cmsdetect.py 27 泉南市 https://www.city.sennan.lg.jp/
python ./cmsdetect.py 27 阪南市 http://www.city.hannan.lg.jp
python ./cmsdetect.py 27 岬町 http://www.town.misaki.osaka.jp/
python ./cmsdetect.py 27 松原市 https://www.city.matsubara.lg.jp/
python ./cmsdetect.py 27 羽曳野市 https://www.city.habikino.lg.jp/
python ./cmsdetect.py 27 藤井寺市 https://www.city.fujiidera.lg.jp/
python ./cmsdetect.py 27 太子町 https://www.town.taishi.osaka.jp/
python ./cmsdetect.py 27 河南町 http://www.town.kanan.osaka.jp/
python ./cmsdetect.py 27 千早赤阪村 http://www.vill.chihayaakasaka.osaka.jp/
python ./cmsdetect.py 27 富田林市 https://www.city.tondabayashi.lg.jp/
python ./cmsdetect.py 27 大阪狭山市 http://www.city.osakasayama.osaka.jp/
python ./cmsdetect.py 27 河内長野市 https://www.city.kawachinagano.lg.jp/
