python ./cmsdetect.py 28 兵庫県 https://web.pref.hyogo.lg.jp/
python ./cmsdetect.py 28 神戸市 https://www.city.kobe.lg.jp/
python ./cmsdetect.py 28 尼崎市 https://www.city.amagasaki.hyogo.jp/
python ./cmsdetect.py 28 西宮市 https://www.nishi.or.jp/
python ./cmsdetect.py 28 芦屋市 https://www.city.ashiya.lg.jp/
python ./cmsdetect.py 28 伊丹市 http://www.city.itami.lg.jp/
python ./cmsdetect.py 28 宝塚市 https://www.city.takarazuka.hyogo.jp/
python ./cmsdetect.py 28 川西市 https://www.city.kawanishi.hyogo.jp/
python ./cmsdetect.py 28 三田市 https://www.city.sanda.lg.jp/
python ./cmsdetect.py 28 猪名川町 https://www.town.inagawa.lg.jp/
python ./cmsdetect.py 28 明石市 http://www.city.akashi.lg.jp/
python ./cmsdetect.py 28 加古川市 https://www.city.kakogawa.lg.jp/
python ./cmsdetect.py 28 高砂市 http://www.city.takasago.lg.jp/
python ./cmsdetect.py 28 稲美町 https://www.town.hyogo-inami.lg.jp/
python ./cmsdetect.py 28 播磨町 http://www.town.harima.lg.jp/
python ./cmsdetect.py 28 西脇市 https://www.city.nishiwaki.lg.jp/
python ./cmsdetect.py 28 三木市 https://www.city.miki.lg.jp/
python ./cmsdetect.py 28 小野市 https://www.city.ono.hyogo.jp/
python ./cmsdetect.py 28 加西市 http://www.city.kasai.hyogo.jp/
python ./cmsdetect.py 28 加東市 https://www.city.kato.lg.jp/
python ./cmsdetect.py 28 多可町 https://www.town.taka.lg.jp/
python ./cmsdetect.py 28 姫路市 https://www.city.himeji.lg.jp/
python ./cmsdetect.py 28 神河町 http://www.town.kamikawa.hyogo.jp/
python ./cmsdetect.py 28 市川町 https://www.town.ichikawa.lg.jp/
python ./cmsdetect.py 28 福崎町 http://www.town.fukusaki.hyogo.jp/
python ./cmsdetect.py 28 相生市 http://www.city.aioi.lg.jp/
python ./cmsdetect.py 28 たつの市 https://www.city.tatsuno.lg.jp/
python ./cmsdetect.py 28 赤穂市 http://www.city.ako.lg.jp/
python ./cmsdetect.py 28 宍粟市 http://www.city.shiso.lg.jp/
python ./cmsdetect.py 28 太子町 http://www.town.hyogo-taishi.lg.jp/
python ./cmsdetect.py 28 上郡町 http://www.town.kamigori.hyogo.jp/
python ./cmsdetect.py 28 佐用町 http://www.town.kamigori.hyogo.jp/
python ./cmsdetect.py 28 豊岡市 https://www.city.toyooka.lg.jp/
python ./cmsdetect.py 28 養父市 https://www.city.yabu.hyogo.jp/
python ./cmsdetect.py 28 朝来市 http://www.city.asago.hyogo.jp/
python ./cmsdetect.py 28 香美町 https://www.town.mikata-kami.lg.jp/
python ./cmsdetect.py 28 新温泉町 https://www.town.shinonsen.hyogo.jp/
python ./cmsdetect.py 28 篠山市 http://www.city.sasayama.hyogo.jp/
python ./cmsdetect.py 28 丹波市 https://www.city.tamba.lg.jp/
python ./cmsdetect.py 28 洲本市 https://www.city.sumoto.lg.jp/
python ./cmsdetect.py 28 南あわじ市 http://www.city.minamiawaji.hyogo.jp/
python ./cmsdetect.py 28 淡路市 http://www.city.awaji.lg.jp/
