python ./cmsdetect.py 3 岩手県 https://www.pref.iwate.jp/
python ./cmsdetect.py 3 盛岡市 http://www.city.morioka.iwate.jp/
python ./cmsdetect.py 3 宮古市 https://www.city.miyako.iwate.jp/
python ./cmsdetect.py 3 大船渡市 https://www.city.ofunato.iwate.jp/
python ./cmsdetect.py 3 花巻市 https://www.city.hanamaki.iwate.jp/
python ./cmsdetect.py 3 北上市 https://www.city.kitakami.iwate.jp/
python ./cmsdetect.py 3 久慈市 https://www.city.kuji.iwate.jp/
python ./cmsdetect.py 3 遠野市 https://www.city.tono.iwate.jp/
python ./cmsdetect.py 3 一関市 https://www.city.ichinoseki.iwate.jp/
python ./cmsdetect.py 3 陸前高田市 http://www.city.rikuzentakata.iwate.jp/
python ./cmsdetect.py 3 釜石市 https://www.city.kamaishi.iwate.jp/
python ./cmsdetect.py 3 二戸市 https://www.city.ninohe.lg.jp/
python ./cmsdetect.py 3 八幡平市 https://www.city.hachimantai.lg.jp/
python ./cmsdetect.py 3 奥州市 https://www.city.oshu.iwate.jp/
python ./cmsdetect.py 3 滝沢市 http://www.city.takizawa.iwate.jp/
python ./cmsdetect.py 3 雫石町 https://www.town.shizukuishi.iwate.jp/
python ./cmsdetect.py 3 葛巻町 https://www.town.kuzumaki.iwate.jp/
python ./cmsdetect.py 3 岩手町 http://www.town.iwate.iwate.jp/
python ./cmsdetect.py 3 紫波町 http://www.town.shiwa.iwate.jp/
python ./cmsdetect.py 3 矢巾町 https://www.town.yahaba.iwate.jp/
python ./cmsdetect.py 3 西和賀町 https://www.town.nishiwaga.lg.jp/
python ./cmsdetect.py 3 金ケ崎町 https://www.town.kanegasaki.iwate.jp/
python ./cmsdetect.py 3 平泉町 https://www.town.hiraizumi.iwate.jp/
python ./cmsdetect.py 3 住田町 https://www.town.sumita.iwate.jp/
python ./cmsdetect.py 3 大槌町 https://www.town.otsuchi.iwate.jp/
python ./cmsdetect.py 3 山田町 https://www.town.yamada.iwate.jp/
python ./cmsdetect.py 3 岩泉町 http://www.town.iwaizumi.iwate.jp/
python ./cmsdetect.py 3 田野畑村 https://www.vill.tanohata.iwate.jp/
python ./cmsdetect.py 3 普代村 https://www.vill.fudai.iwate.jp/
python ./cmsdetect.py 3 軽米町 http://www.town.karumai.iwate.jp/
python ./cmsdetect.py 3 野田村 http://www.vill.noda.iwate.jp/
python ./cmsdetect.py 3 九戸村 http://www.vill.kunohe.iwate.jp/
python ./cmsdetect.py 3 洋野町 http://www.town.hirono.iwate.jp/
python ./cmsdetect.py 3 一戸町 https://www.town.ichinohe.iwate.jp/
