python ./cmsdetect.py 30 和歌山県 https://www.pref.wakayama.lg.jp/
python ./cmsdetect.py 30 和歌山市 http://www.city.wakayama.wakayama.jp/
python ./cmsdetect.py 30 海南市 http://www.city.kainan.wakayama.jp/
python ./cmsdetect.py 30 橋本市 http://www.city.hashimoto.lg.jp/
python ./cmsdetect.py 30 有田市 https://www.city.arida.lg.jp/
python ./cmsdetect.py 30 御坊市 http://www.city.gobo.wakayama.jp/
python ./cmsdetect.py 30 田辺市 http://www.city.tanabe.lg.jp/
python ./cmsdetect.py 30 新宮市 https://www.city.shingu.lg.jp/
python ./cmsdetect.py 30 紀の川市 http://www.city.kinokawa.lg.jp/
python ./cmsdetect.py 30 岩出市 https://www.city.iwade.lg.jp/
python ./cmsdetect.py 30 紀美野町 http://www.town.kimino.wakayama.jp/
python ./cmsdetect.py 30 かつらぎ町 http://www.town.katsuragi.wakayama.jp/
python ./cmsdetect.py 30 九度山町 https://www.town.kudoyama.wakayama.jp/
python ./cmsdetect.py 30 高野町 http://www.town.koya.wakayama.jp/
python ./cmsdetect.py 30 湯浅町 http://www.town.yuasa.wakayama.jp/
python ./cmsdetect.py 30 広川町 https://www.town.hirogawa.wakayama.jp/
python ./cmsdetect.py 30 有田川町 https://www.town.aridagawa.lg.jp/
python ./cmsdetect.py 30 美浜町 http://www.town.mihama.wakayama.jp/
python ./cmsdetect.py 30 日高町 http://www.town.wakayama-hidaka.lg.jp/
python ./cmsdetect.py 30 由良町 http://www.town.yura.wakayama.jp/
python ./cmsdetect.py 30 印南町 http://www.town.wakayama-inami.lg.jp/
python ./cmsdetect.py 30 みなべ町 http://www.town.minabe.lg.jp/
python ./cmsdetect.py 30 日高川町 http://www.town.hidakagawa.lg.jp/
python ./cmsdetect.py 30 白浜町 http://www.town.shirahama.wakayama.jp/
python ./cmsdetect.py 30 上富田町 http://www.town.kamitonda.lg.jp/
python ./cmsdetect.py 30 すさみ町 http://www.town.susami.lg.jp/
python ./cmsdetect.py 30 那智勝浦町 https://www.town.nachikatsuura.wakayama.jp/
python ./cmsdetect.py 30 太地町 http://www.town.taiji.wakayama.jp/
python ./cmsdetect.py 30 古座川町 http://www.town.kozagawa.wakayama.jp/
python ./cmsdetect.py 30 北山村 https://www.vill.kitayama.wakayama.jp/
python ./cmsdetect.py 30 串本町 https://www.town.kushimoto.wakayama.jp/
