#!/bin/sh
python ./cmsdetect.py 33 岡山県 https://www.pref.okayama.jp/
python ./cmsdetect.py 33 岡山市 https://www.city.okayama.jp/
python ./cmsdetect.py 33 美作市 http://www.city.mimasaka.lg.jp/
python ./cmsdetect.py 33 津山市 https://www.city.tsuyama.lg.jp/
python ./cmsdetect.py 33 玉野市 https://www.city.tamano.lg.jp/
python ./cmsdetect.py 33 笠岡市 http://www.city.kasaoka.okayama.jp/
python ./cmsdetect.py 33 井原市 http://www.city.ibara.okayama.jp/
python ./cmsdetect.py 33 総社市 http://www.city.soja.okayama.jp/
python ./cmsdetect.py 33 高梁市 http://www.city.takahashi.okayama.jp/
python ./cmsdetect.py 33 新見市 https://www.city.niimi.okayama.jp/
python ./cmsdetect.py 33 備前市 https://www.city.bizen.okayama.jp/
python ./cmsdetect.py 33 瀬戸内市 http://www.city.setouchi.lg.jp/
python ./cmsdetect.py 33 赤磐市 https://www.city.akaiwa.lg.jp/
python ./cmsdetect.py 33 真庭市 https://www.city.maniwa.lg.jp/
python ./cmsdetect.py 33 吉備中央町 http://www.town.kibichuo.lg.jp/
python ./cmsdetect.py 33 倉敷市 https://www.city.kurashiki.okayama.jp/
python ./cmsdetect.py 33 浅口市 http://www.city.asakuchi.lg.jp/
python ./cmsdetect.py 33 和気町 https://www.town.wake.lg.jp/
python ./cmsdetect.py 33 早島町 http://www.town.hayashima.lg.jp/
python ./cmsdetect.py 33 里庄町 http://www.town.satosho.okayama.jp/
python ./cmsdetect.py 33 矢掛町 http://www.town.yakage.okayama.jp/
python ./cmsdetect.py 33 新庄村 http://www.vill.shinjo.okayama.jp/
python ./cmsdetect.py 33 鏡野町 http://www.town.kagamino.lg.jp/
python ./cmsdetect.py 33 勝央町 http://www.town.shoo.lg.jp/
python ./cmsdetect.py 33 奈義町 https://www.town.nagi.okayama.jp/
python ./cmsdetect.py 33 西粟倉村 http://www.vill.nishiawakura.okayama.jp/wp/
python ./cmsdetect.py 33 久米南町 https://www.town.kumenan.lg.jp/
python ./cmsdetect.py 33 美咲町 http://www.town.misaki.okayama.jp/
