#!/bin/sh
python ./cmsdetect.py 34 広島県 https://www.pref.hiroshima.lg.jp/
python ./cmsdetect.py 34 広島市 https://www.city.hiroshima.lg.jp/
python ./cmsdetect.py 34 呉市 http://www.city.kure.lg.jp/
python ./cmsdetect.py 34 竹原市 https://www.city.takehara.lg.jp/
python ./cmsdetect.py 34 三原市 https://www.city.mihara.hiroshima.jp/
python ./cmsdetect.py 34 尾道市 https://www.city.onomichi.hiroshima.jp/
python ./cmsdetect.py 34 福山市 https://www.city.fukuyama.hiroshima.jp/
python ./cmsdetect.py 34 府中市 http://www.city.fuchu.hiroshima.jp/
python ./cmsdetect.py 34 三次市 https://www.city.miyoshi.hiroshima.jp/
python ./cmsdetect.py 34 庄原市 http://www.city.shobara.hiroshima.jp/
python ./cmsdetect.py 34 大竹市 http://www.city.otake.hiroshima.jp/
python ./cmsdetect.py 34 東広島市 https://www.city.higashihiroshima.lg.jp/
python ./cmsdetect.py 34 廿日市市 http://www.city.hatsukaichi.hiroshima.jp/
python ./cmsdetect.py 34 安芸高田市 https://www.akitakata.jp/ja/
python ./cmsdetect.py 34 江田島市 https://www.city.etajima.hiroshima.jp/cms/
python ./cmsdetect.py 34 府中町 https://www.town.fuchu.hiroshima.jp/
python ./cmsdetect.py 34 海田町 https://www.town.kaita.lg.jp/
python ./cmsdetect.py 34 熊野町 https://www.town.kumano.hiroshima.jp/
python ./cmsdetect.py 34 坂町 http://www.town.saka.lg.jp/
python ./cmsdetect.py 34 安芸太田町 http://www.akiota.jp/
python ./cmsdetect.py 34 北広島町 https://www.town.kitahiroshima.lg.jp/
python ./cmsdetect.py 34 大崎上島町 https://www.town.osakikamijima.hiroshima.jp/
python ./cmsdetect.py 34 世羅町 http://www.town.sera.hiroshima.jp/
python ./cmsdetect.py 34 神石高原町 http://www.jinsekigun.jp/
