python ./cmsdetect.py 39 高知県 https://www.pref.kochi.lg.jp/
python ./cmsdetect.py 39 高知市 https://www.city.kochi.kochi.jp/
python ./cmsdetect.py 39 室戸市 https://www.city.muroto.kochi.jp/
python ./cmsdetect.py 39 安芸市 https://www.city.aki.kochi.jp/
python ./cmsdetect.py 39 南国市 https://www.city.nankoku.lg.jp/
python ./cmsdetect.py 39 土佐市 http://www.city.tosa.lg.jp/
python ./cmsdetect.py 39 須崎市 https://www.city.susaki.lg.jp/
python ./cmsdetect.py 39 宿毛市 https://www.city.sukumo.kochi.jp/
python ./cmsdetect.py 39 土佐清水市 https://www.city.tosashimizu.kochi.jp/
python ./cmsdetect.py 39 四万十市 http://www.city.shimanto.lg.jp/
python ./cmsdetect.py 39 香南市 https://www.city.kochi-konan.lg.jp/
python ./cmsdetect.py 39 香美市 https://www.city.kami.lg.jp/
python ./cmsdetect.py 39 東洋町 http://www.town.toyo.kochi.jp/
python ./cmsdetect.py 39 奈半利町 http://www.town.nahari.kochi.jp/
python ./cmsdetect.py 39 田野町 https://tanocho.jp/
python ./cmsdetect.py 39 安田町 https://www.town.yasuda.kochi.jp/
python ./cmsdetect.py 39 北川村 http://www.kitagawamura.jp/
python ./cmsdetect.py 39 馬路村 http://www.vill.umaji.kochi.jp/
python ./cmsdetect.py 39 芸西村 http://www.vill.geisei.kochi.jp/
python ./cmsdetect.py 39 本山町 http://www.town.motoyama.kochi.jp/
python ./cmsdetect.py 39 大豊町 http://www.town.otoyo.kochi.jp/
python ./cmsdetect.py 39 土佐町 http://www.town.tosa.kochi.jp/
python ./cmsdetect.py 39 大川村 http://www.vill.okawa.kochi.jp/
python ./cmsdetect.py 39 いの町 http://www.town.ino.kochi.jp/
python ./cmsdetect.py 39 仁淀川町 https://www.town.niyodogawa.lg.jp/
python ./cmsdetect.py 39 中土佐町 https://www.town.nakatosa.lg.jp/
python ./cmsdetect.py 39 佐川町 https://www.town.sakawa.lg.jp/
python ./cmsdetect.py 39 越知町 http://www.town.ochi.kochi.jp/
python ./cmsdetect.py 39 檮原町 http://www.town.yusuhara.kochi.jp/town/
python ./cmsdetect.py 39 日高村 https://www.vill.hidaka.kochi.jp/
python ./cmsdetect.py 39 津野町 https://town.kochi-tsuno.lg.jp/
python ./cmsdetect.py 39 四万十町 https://www.town.shimanto.lg.jp/
python ./cmsdetect.py 39 大月町 https://www.town.otsuki.kochi.jp/
python ./cmsdetect.py 39 三原村 http://www.vill.mihara.kochi.jp/
python ./cmsdetect.py 39 黒潮町 https://www.town.kuroshio.lg.jp/
