python ./cmsdetect.py 4 宮城県 https://www.pref.miyagi.jp/
python ./cmsdetect.py 4 仙台市 http://www.city.sendai.jp/
python ./cmsdetect.py 4 石巻市 https://www.city.ishinomaki.lg.jp/
python ./cmsdetect.py 4 塩竈市 https://www.city.shiogama.miyagi.jp/
python ./cmsdetect.py 4 気仙沼市 https://www.kesennuma.miyagi.jp/
python ./cmsdetect.py 4 白石市 https://www.city.shiroishi.miyagi.jp/
python ./cmsdetect.py 4 名取市 https://www.city.natori.miyagi.jp/
python ./cmsdetect.py 4 角田市 https://www.city.kakuda.lg.jp/
python ./cmsdetect.py 4 多賀城市 http://www.city.tagajo.miyagi.jp/
python ./cmsdetect.py 4 岩沼市 https://www.city.iwanuma.miyagi.jp/
python ./cmsdetect.py 4 登米市 https://www.city.tome.miyagi.jp/
python ./cmsdetect.py 4 栗原市 https://www.kuriharacity.jp/
python ./cmsdetect.py 4 東松島市 http://www.city.higashimatsushima.miyagi.jp/
python ./cmsdetect.py 4 大崎市 http://www.city.osaki.miyagi.jp/
python ./cmsdetect.py 4 富谷市 https://www.tomiya-city.miyagi.jp/
python ./cmsdetect.py 4 蔵王町 https://www.town.zao.miyagi.jp/
python ./cmsdetect.py 4 七ヶ宿町 https://town.shichikashuku.miyagi.jp/
python ./cmsdetect.py 4 大河原町 https://www.town.ogawara.miyagi.jp/
python ./cmsdetect.py 4 村田町 http://www.town.murata.miyagi.jp/
python ./cmsdetect.py 4 柴田町 https://www.town.shibata.miyagi.jp/
python ./cmsdetect.py 4 川崎町 http://www.town.kawasaki.miyagi.jp/
python ./cmsdetect.py 4 丸森町 http://www.town.marumori.miyagi.jp/
python ./cmsdetect.py 4 亘理町 http://www.town.watari.miyagi.jp/
python ./cmsdetect.py 4 山元町 https://www.town.yamamoto.miyagi.jp/
python ./cmsdetect.py 4 松島町 http://www.town.miyagi-matsushima.lg.jp/
python ./cmsdetect.py 4 七ヶ浜町 https://www.shichigahama.com/
python ./cmsdetect.py 4 利府町 https://www.town.rifu.miyagi.jp/
python ./cmsdetect.py 4 大和町 https://www.town.taiwa.miyagi.jp/
python ./cmsdetect.py 4 大郷町 http://www.town.miyagi-osato.lg.jp/
python ./cmsdetect.py 4 大衡村 http://www.village.ohira.miyagi.jp/
python ./cmsdetect.py 4 色麻町 http://www.town.shikama.miyagi.jp/
python ./cmsdetect.py 4 加美町 http://www.town.kami.miyagi.jp/
python ./cmsdetect.py 4 涌谷町 http://www.town.wakuya.miyagi.jp/
python ./cmsdetect.py 4 美里町 https://www.town.misato.miyagi.jp/
python ./cmsdetect.py 4 女川町 https://www.town.onagawa.miyagi.jp/
python ./cmsdetect.py 4 南三陸町 http://www.town.minamisanriku.miyagi.jp/
