#!/bin/sh
python ./cmsdetect.py 40 福岡県 https://www.pref.fukuoka.lg.jp/
python ./cmsdetect.py 40 北九州市 https://www.city.kitakyushu.lg.jp/
python ./cmsdetect.py 40 福岡市 https://www.city.fukuoka.lg.jp/index.html
python ./cmsdetect.py 40 大牟田市 https://www.city.omuta.lg.jp/
python ./cmsdetect.py 40 久留米市 https://www.city.kurume.fukuoka.jp/
python ./cmsdetect.py 40 直方市 https://www.city.nogata.fukuoka.jp/
python ./cmsdetect.py 40 飯塚市 https://www.city.iizuka.lg.jp/
python ./cmsdetect.py 40 田川市 https://www.joho.tagawa.fukuoka.jp/
python ./cmsdetect.py 40 柳川市 https://www.city.yanagawa.fukuoka.jp/
python ./cmsdetect.py 40 八女市 https://www.city.yame.fukuoka.jp/
python ./cmsdetect.py 40 筑後市 https://www.city.chikugo.lg.jp/
python ./cmsdetect.py 40 大川市 http://www.city.okawa.lg.jp/
python ./cmsdetect.py 40 行橋市 http://www.city.yukuhashi.fukuoka.jp/
python ./cmsdetect.py 40 豊前市 http://www.city.buzen.lg.jp/
python ./cmsdetect.py 40 中間市 http://www.city.nakama.lg.jp/
python ./cmsdetect.py 40 小郡市 https://www.city.ogori.fukuoka.jp/
python ./cmsdetect.py 40 筑紫野市 https://www.city.chikushino.fukuoka.jp/
python ./cmsdetect.py 40 春日市 https://www.city.kasuga.fukuoka.jp/
python ./cmsdetect.py 40 大野城市 http://www.city.onojo.fukuoka.jp/
python ./cmsdetect.py 40 宗像市 https://www.city.munakata.lg.jp/
python ./cmsdetect.py 40 太宰府市 http://www.city.dazaifu.lg.jp/
python ./cmsdetect.py 40 古賀市 https://www.city.koga.fukuoka.jp/
python ./cmsdetect.py 40 福津市 https://www.city.fukutsu.lg.jp/
python ./cmsdetect.py 40 うきは市 http://www.city.ukiha.fukuoka.jp/
python ./cmsdetect.py 40 宮若市 https://www.city.miyawaka.lg.jp/
python ./cmsdetect.py 40 嘉麻市 https://www.city.kama.lg.jp/
python ./cmsdetect.py 40 朝倉市 http://www.city.asakura.lg.jp/
python ./cmsdetect.py 40 みやま市 http://www.city.miyama.lg.jp/
python ./cmsdetect.py 40 糸島市 https://www.city.itoshima.lg.jp/
python ./cmsdetect.py 40 那珂川市 https://www.city.nakagawa.lg.jp/
python ./cmsdetect.py 40 宇美町 http://www.town.umi.lg.jp/
python ./cmsdetect.py 40 篠栗町 https://www.town.sasaguri.fukuoka.jp/
python ./cmsdetect.py 40 志免町 http://www.town.shime.lg.jp/
python ./cmsdetect.py 40 須恵町 http://www.town.sue.fukuoka.jp/
python ./cmsdetect.py 40 新宮町 http://www.town.shingu.fukuoka.jp/
python ./cmsdetect.py 40 久山町 http://www.town.hisayama.fukuoka.jp/
python ./cmsdetect.py 40 粕屋町 https://www.town.kasuya.fukuoka.jp/
python ./cmsdetect.py 40 芦屋町 https://www.town.ashiya.lg.jp/
python ./cmsdetect.py 40 水巻町 https://www.town.mizumaki.lg.jp/
python ./cmsdetect.py 40 岡垣町 http://www.town.okagaki.lg.jp/
python ./cmsdetect.py 40 遠賀町 http://www.town.onga.lg.jp/
python ./cmsdetect.py 40 小竹町 https://town.kotake.lg.jp/
python ./cmsdetect.py 40 鞍手町 http://www.town.kurate.lg.jp/
python ./cmsdetect.py 40 桂川町 http://www.town.keisen.fukuoka.jp/
python ./cmsdetect.py 40 筑前町 https://www.town.chikuzen.fukuoka.jp/
python ./cmsdetect.py 40 東峰村 http://vill.toho-info.com/
python ./cmsdetect.py 40 大刀洗町 http://www.town.tachiarai.fukuoka.jp/
python ./cmsdetect.py 40 大木町 https://www.town.ooki.lg.jp/
python ./cmsdetect.py 40 広川町 http://www.town.hirokawa.fukuoka.jp/
python ./cmsdetect.py 40 香春町 https://www.town.kawara.fukuoka.jp/
python ./cmsdetect.py 40 添田町 http://www.town.soeda.fukuoka.jp/
python ./cmsdetect.py 40 糸田町 http://www.town.itoda.lg.jp/
python ./cmsdetect.py 40 川崎町 https://www.town-kawasaki.com/
python ./cmsdetect.py 40 大任町 http://www.town.oto.fukuoka.jp/
python ./cmsdetect.py 40 福智町 http://www.town.fukuchi.fukuoka.jp/
python ./cmsdetect.py 40 赤村 http://www.akamura.net/
python ./cmsdetect.py 40 苅田町 https://www.town.kanda.lg.jp/
python ./cmsdetect.py 40 みやこ町 http://www.town.miyako.lg.jp/
python ./cmsdetect.py 40 吉富町 http://www.town.yoshitomi.lg.jp/
python ./cmsdetect.py 40 上毛町 https://www.town.koge.lg.jp/
python ./cmsdetect.py 40 築上町 https://www.town.chikujo.fukuoka.jp/
