python ./cmsdetect.py 41 佐賀県 https://www.pref.saga.lg.jp/
python ./cmsdetect.py 41 佐賀市 https://www.city.saga.lg.jp/
python ./cmsdetect.py 41 唐津市 https://www.city.karatsu.lg.jp/
python ./cmsdetect.py 41 鳥栖市 https://www.city.tosu.lg.jp/
python ./cmsdetect.py 41 多久市 https://www.city.taku.lg.jp/
python ./cmsdetect.py 41 伊万里市 https://www.city.imari.saga.jp/
python ./cmsdetect.py 41 武雄市 https://www.city.takeo.lg.jp/
python ./cmsdetect.py 41 鹿島市 https://www.city.saga-kashima.lg.jp/
python ./cmsdetect.py 41 小城市 https://www.city.ogi.lg.jp/
python ./cmsdetect.py 41 嬉野市 https://www.city.ureshino.lg.jp/
python ./cmsdetect.py 41 神埼市 https://www.city.kanzaki.saga.jp/
python ./cmsdetect.py 41 吉野ヶ里町 https://www.town.yoshinogari.lg.jp/
python ./cmsdetect.py 41 基山町 https://www.town.kiyama.lg.jp/
python ./cmsdetect.py 41 上峰町 https://www.town.kamimine.lg.jp/
python ./cmsdetect.py 41 みやき町 https://www.town.miyaki.lg.jp/
python ./cmsdetect.py 41 玄海町 https://www.town.genkai.lg.jp/
python ./cmsdetect.py 41 有田町 https://www.town.arita.lg.jp/
python ./cmsdetect.py 41 大町町 http://www.town.omachi.saga.jp/
python ./cmsdetect.py 41 江北町 https://www.town.kouhoku.saga.jp/
python ./cmsdetect.py 41 白石町 https://www.town.shiroishi.lg.jp/
python ./cmsdetect.py 41 太良町 https://www.town.tara.lg.jp/
