python ./cmsdetect.py 42 長崎県 https://www.pref.nagasaki.jp/
python ./cmsdetect.py 42 長崎市 https://www.city.nagasaki.lg.jp/
python ./cmsdetect.py 42 佐世保市 https://www.city.sasebo.lg.jp/
python ./cmsdetect.py 42 島原市 https://www.city.shimabara.lg.jp/
python ./cmsdetect.py 42 諫早市 https://www.city.isahaya.nagasaki.jp/
python ./cmsdetect.py 42 大村市 http://www.city.omura.nagasaki.jp/
python ./cmsdetect.py 42 平戸市 https://www.city.hirado.nagasaki.jp/
python ./cmsdetect.py 42 松浦市 https://www.city-matsuura.jp/
python ./cmsdetect.py 42 対馬市 http://www.city.tsushima.nagasaki.jp/
python ./cmsdetect.py 42 壱岐市 http://www.city.iki.nagasaki.jp/
python ./cmsdetect.py 42 五島市 https://www.city.goto.nagasaki.jp/
python ./cmsdetect.py 42 西海市 https://www.city.saikai.nagasaki.jp/
python ./cmsdetect.py 42 雲仙市 http://www.city.unzen.nagasaki.jp/
python ./cmsdetect.py 42 南島原市 https://www.city.minamishimabara.lg.jp/
python ./cmsdetect.py 42 長与町 https://webtown.nagayo.jp/
python ./cmsdetect.py 42 時津町 https://www.town.togitsu.nagasaki.jp/
python ./cmsdetect.py 42 東彼杵町 http://www.sonogi.jp/
python ./cmsdetect.py 42 川棚町 http://www.kawatana.jp/
python ./cmsdetect.py 42 波佐見町 https://www.town.hasami.lg.jp/
python ./cmsdetect.py 42 小値賀町 http://ojika.net/
python ./cmsdetect.py 42 佐々町 https://www.sazacho-nagasaki.jp/
python ./cmsdetect.py 42 新上五島町 https://official.shinkamigoto.net/
