python ./cmsdetect.py 43 熊本県 https://www.pref.kumamoto.jp/
python ./cmsdetect.py 43 熊本市 https://www.city.kumamoto.jp/
python ./cmsdetect.py 43 八代市 http://www.city.yatsushiro.lg.jp/
python ./cmsdetect.py 43 人吉市 https://www.city.hitoyoshi.lg.jp/
python ./cmsdetect.py 43 荒尾市 https://www.city.arao.lg.jp/
python ./cmsdetect.py 43 水俣市 https://www.city.minamata.lg.jp/
python ./cmsdetect.py 43 玉名市 https://www.city.tamana.lg.jp/
python ./cmsdetect.py 43 天草市 https://www.city.amakusa.kumamoto.jp/
python ./cmsdetect.py 43 山鹿市 https://www.city.yamaga.kumamoto.jp/
python ./cmsdetect.py 43 菊池市 https://www.city.kikuchi.lg.jp/
python ./cmsdetect.py 43 宇土市 https://www.city.uto.lg.jp/
python ./cmsdetect.py 43 上天草市 https://www.city.kamiamakusa.kumamoto.jp/
python ./cmsdetect.py 43 宇城市 https://www.city.uki.kumamoto.jp/
python ./cmsdetect.py 43 阿蘇市 http://www.city.aso.kumamoto.jp/
python ./cmsdetect.py 43 合志市 https://www.city.koshi.lg.jp/
python ./cmsdetect.py 43 美里町 https://www.town.kumamoto-misato.lg.jp/
python ./cmsdetect.py 43 玉東町 http://www.town.gyokuto.kumamoto.jp/
python ./cmsdetect.py 43 和水町 https://www.town.nagomi.lg.jp/
python ./cmsdetect.py 43 南関町 https://www.town.nankan.lg.jp/
python ./cmsdetect.py 43 長洲町 https://www.town.nagasu.lg.jp/
python ./cmsdetect.py 43 大津町 https://www.town.nagasu.lg.jp/
python ./cmsdetect.py 43 菊陽町 https://www.town.kikuyo.lg.jp/
python ./cmsdetect.py 43 南小国町 https://www.town.minamioguni.lg.jp/
python ./cmsdetect.py 43 小国町 https://www.town.kumamoto-oguni.lg.jp/
python ./cmsdetect.py 43 産山村 http://www.ubuyama-v.jp/
python ./cmsdetect.py 43 高森町 http://www.town.takamori.kumamoto.jp/
python ./cmsdetect.py 43 南阿蘇村 http://www.vill.minamiaso.lg.jp/
python ./cmsdetect.py 43 西原村 https://www.vill.nishihara.kumamoto.jp/
python ./cmsdetect.py 43 御船町 https://www.town.mifune.kumamoto.jp/
python ./cmsdetect.py 43 嘉島町 https://www.town.kumamoto-kashima.lg.jp/
python ./cmsdetect.py 43 益城町 https://www.town.mashiki.lg.jp/
python ./cmsdetect.py 43 甲佐町 https://www.town.kosa.lg.jp/
python ./cmsdetect.py 43 山都町 https://www.town.kumamoto-yamato.lg.jp/
python ./cmsdetect.py 43 氷川町 http://www.hikawacyou.hinokuni-net.jp/
python ./cmsdetect.py 43 芦北町 http://www.ashikita-t.kumamoto-sgn.jp/
python ./cmsdetect.py 43 津奈木町 http://www.town.tsunagi.lg.jp/
python ./cmsdetect.py 43 錦町 http://www.nishiki-machi.com/
python ./cmsdetect.py 43 あさぎり町 https://www.town.asagiri.lg.jp/
python ./cmsdetect.py 43 多良木町 https://www.town.taragi.lg.jp/
python ./cmsdetect.py 43 湯前町 https://www.town.yunomae.lg.jp/
python ./cmsdetect.py 43 水上村 https://www.vill.mizukami.lg.jp/
python ./cmsdetect.py 43 相良村 https://www.vill.sagara.lg.jp/
python ./cmsdetect.py 43 五木村 https://www.vill.itsuki.lg.jp/
python ./cmsdetect.py 43 山江村 https://www.vill.yamae.lg.jp/
python ./cmsdetect.py 43 球磨村 http://www.kumamura.com/gyousei/
python ./cmsdetect.py 43 苓北町 https://reihoku-kumamoto.jp/

