python ./cmsdetect.py 44 大分県 https://www.pref.oita.jp/
python ./cmsdetect.py 44 大分市 http://www.city.oita.oita.jp/
python ./cmsdetect.py 44 別府市 https://www.city.beppu.oita.jp/
python ./cmsdetect.py 44 中津市 https://www.city-nakatsu.jp/
python ./cmsdetect.py 44 日田市 https://www.city.hita.oita.jp/
python ./cmsdetect.py 44 佐伯市 https://www.city.saiki.oita.jp/
python ./cmsdetect.py 44 臼杵市 https://www.city.usuki.oita.jp/
python ./cmsdetect.py 44 津久見市 http://www.city.tsukumi.oita.jp/
python ./cmsdetect.py 44 竹田市 https://www.city.taketa.oita.jp/
python ./cmsdetect.py 44 豊後高田市 https://www.city.bungotakada.oita.jp/
python ./cmsdetect.py 44 杵築市 http://www.city.kitsuki.lg.jp/
python ./cmsdetect.py 44 宇佐市 https://www.city.usa.oita.jp/
python ./cmsdetect.py 44 豊後大野市 https://www.bungo-ohno.jp/
python ./cmsdetect.py 44 由布市 http://www.city.yufu.oita.jp/
python ./cmsdetect.py 44 国東市 https://www.city.kunisaki.oita.jp/
python ./cmsdetect.py 44 姫島村 https://www.himeshima.jp/
python ./cmsdetect.py 44 日出町 https://www.town.hiji.lg.jp/
python ./cmsdetect.py 44 九重町 https://www.town.kokonoe.oita.jp/
python ./cmsdetect.py 44 玖珠町 https://www.town.kusu.oita.jp/
