python ./cmsdetect.py 46 鹿児島県 https://www.pref.kagoshima.jp/
python ./cmsdetect.py 46 鹿児島市 http://www.city.kagoshima.lg.jp/
python ./cmsdetect.py 46 鹿屋市 https://www.city.kanoya.lg.jp/
python ./cmsdetect.py 46 枕崎市 http://www.city.makurazaki.lg.jp/
python ./cmsdetect.py 46 阿久根市 http://www.city.akune.kagoshima.jp/
python ./cmsdetect.py 46 出水市 https://www.city.kagoshima-izumi.lg.jp/
python ./cmsdetect.py 46 指宿市 https://www.city.ibusuki.lg.jp/
python ./cmsdetect.py 46 西之表市 http://www.city.nishinoomote.lg.jp/
python ./cmsdetect.py 46 垂水市 http://www.city.tarumizu.lg.jp/
python ./cmsdetect.py 46 薩摩川内市 https://www.city.satsumasendai.lg.jp/
python ./cmsdetect.py 46 日置市 http://www.city.hioki.kagoshima.jp/
python ./cmsdetect.py 46 曽於市 https://www.city.soo.kagoshima.jp/
python ./cmsdetect.py 46 霧島市 http://www.city-kirishima.jp/
python ./cmsdetect.py 46 いちき串木野市 http://www.city.ichikikushikino.lg.jp/
python ./cmsdetect.py 46 南さつま市 http://www.city.minamisatsuma.lg.jp/
python ./cmsdetect.py 46 志布志市 https://www.city.shibushi.lg.jp/
python ./cmsdetect.py 46 奄美市 http://www.city.amami.lg.jp/
python ./cmsdetect.py 46 南九州市 http://www.city.minamikyushu.lg.jp/
python ./cmsdetect.py 46 伊佐市 https://www.city.isa.kagoshima.jp/
python ./cmsdetect.py 46 姶良市 http://www.city.aira.lg.jp/
python ./cmsdetect.py 46 三島村 http://mishimamura.com/
python ./cmsdetect.py 46 十島村 http://www.tokara.jp/
python ./cmsdetect.py 46 さつま町 http://www.satsuma-net.jp/
python ./cmsdetect.py 46 長島町 https://www.town.nagashima.lg.jp/
python ./cmsdetect.py 46 湧水町 http://www.town.yusui.kagoshima.jp/
python ./cmsdetect.py 46 大崎町 http://www.town.kagoshima-osaki.lg.jp/
python ./cmsdetect.py 46 東串良町 http://www.higashikushira.com/
python ./cmsdetect.py 46 錦江町 http://www.town.kinko.lg.jp/
python ./cmsdetect.py 46 南大隅町 http://www.town.minamiosumi.lg.jp/
python ./cmsdetect.py 46 肝付町 https://kimotsuki-town.jp/
python ./cmsdetect.py 46 中種子町 http://town.nakatane.kagoshima.jp/
python ./cmsdetect.py 46 南種子町 http://www.town.minamitane.kagoshima.jp/
python ./cmsdetect.py 46 屋久島町 http://www.town.yakushima.kagoshima.jp/
python ./cmsdetect.py 46 大和村 http://www.vill.yamato.lg.jp/
python ./cmsdetect.py 46 宇検村 http://www.uken.net/
python ./cmsdetect.py 46 瀬戸内町 http://www.town.setouchi.lg.jp/
python ./cmsdetect.py 46 龍郷町 http://www.town.tatsugo.lg.jp/
python ./cmsdetect.py 46 喜界町 http://www.town.kikai.lg.jp/
python ./cmsdetect.py 46 徳之島町 http://www.tokunoshima-town.org/
python ./cmsdetect.py 46 天城町 https://www.town.amagi.lg.jp/
python ./cmsdetect.py 46 伊仙町 http://www.town.isen.kagoshima.jp/
python ./cmsdetect.py 46 和泊町 http://www.town.wadomari.lg.jp/
python ./cmsdetect.py 46 知名町 http://www.town.china.lg.jp/
python ./cmsdetect.py 46 与論町 http://www.yoron.jp/

