python ./cmsdetect.py 47 沖縄県 https://www.pref.okinawa.jp/
python ./cmsdetect.py 47 那覇市 https://www.city.naha.okinawa.jp/
python ./cmsdetect.py 47 宜野湾市 https://www.city.ginowan.lg.jp/
python ./cmsdetect.py 47 石垣市 https://www.city.ishigaki.okinawa.jp/
python ./cmsdetect.py 47 浦添市 http://www.city.urasoe.lg.jp/
python ./cmsdetect.py 47 名護市 http://www.city.nago.okinawa.jp/
python ./cmsdetect.py 47 糸満市 http://www.city.itoman.lg.jp/
python ./cmsdetect.py 47 沖縄市 https://www.city.okinawa.okinawa.jp/
python ./cmsdetect.py 47 豊見城市 https://www.city.tomigusuku.lg.jp/
python ./cmsdetect.py 47 うるま市 https://www.city.uruma.lg.jp/
python ./cmsdetect.py 47 宮古島市 https://www.city.miyakojima.lg.jp/
python ./cmsdetect.py 47 南城市 https://www.city.nanjo.okinawa.jp/
python ./cmsdetect.py 47 国頭村 http://www.vill.kunigami.okinawa.jp/kunigami-village/
python ./cmsdetect.py 47 大宜味村 http://www.vill.ogimi.okinawa.jp/
python ./cmsdetect.py 47 東村 http://www.vill.higashi.okinawa.jp/
python ./cmsdetect.py 47 今帰仁村 https://www.nakijin.jp/
python ./cmsdetect.py 47 本部町 https://www.city.nanjo.okinawa.jp/
python ./cmsdetect.py 47 恩納村 http://www.vill.onna.okinawa.jp/
python ./cmsdetect.py 47 宜野座村 http://www.vill.ginoza.okinawa.jp/news/
python ./cmsdetect.py 47 金武町 https://www.town.kin.okinawa.jp/
python ./cmsdetect.py 47 伊江村 https://www.iejima.org/
python ./cmsdetect.py 47 読谷村 https://www.vill.yomitan.okinawa.jp/
python ./cmsdetect.py 47 嘉手納町 https://www.town.kadena.okinawa.jp/
python ./cmsdetect.py 47 北谷町 http://www.chatan.jp/
python ./cmsdetect.py 47 北中城村 http://www.vill.kitanakagusuku.lg.jp/
python ./cmsdetect.py 47 中城村 https://www.vill.nakagusuku.okinawa.jp/
python ./cmsdetect.py 47 西原町 http://www.town.nishihara.okinawa.jp/
python ./cmsdetect.py 47 与那原町 http://www.town.yonabaru.okinawa.jp/
python ./cmsdetect.py 47 南風原町 http://www.town.haebaru.lg.jp/
python ./cmsdetect.py 47 渡嘉敷村 http://www.vill.tokashiki.okinawa.jp/
python ./cmsdetect.py 47 座間味村 https://www.vill.zamami.okinawa.jp/
python ./cmsdetect.py 47 粟国村 http://www.vill.aguni.okinawa.jp/
python ./cmsdetect.py 47 渡名喜村 http://www.vill.tonaki.okinawa.jp/
python ./cmsdetect.py 47 南大東村 http://www.vill.minamidaito.okinawa.jp/
python ./cmsdetect.py 47 北大東村 http://vill.kitadaito.okinawa.jp/
python ./cmsdetect.py 47 伊平屋村 http://www.vill.iheya.okinawa.jp/
python ./cmsdetect.py 47 伊是名村 https://vill.izena.okinawa.jp/
python ./cmsdetect.py 47 久米島町 http://www.town.kumejima.okinawa.jp/
python ./cmsdetect.py 47 八重瀬町 https://www.town.yaese.lg.jp/
python ./cmsdetect.py 47 多良間村 http://www.vill.tarama.okinawa.jp/
python ./cmsdetect.py 47 竹富町 https://www.town.taketomi.lg.jp/
python ./cmsdetect.py 47 与那国町 https://www.town.yonaguni.okinawa.jp/
