python ./cmsdetect.py 5 秋田県 https://www.pref.akita.lg.jp/
python ./cmsdetect.py 5 鹿角市 https://www.city.kazuno.akita.jp/
python ./cmsdetect.py 5 小坂町 https://www.town.kosaka.akita.jp/
python ./cmsdetect.py 5 大館市 https://www.city.odate.lg.jp/city/
python ./cmsdetect.py 5 北秋田市 https://www.city.kitaakita.akita.jp/
python ./cmsdetect.py 5 上小阿仁村 https://www.vill.kamikoani.akita.jp/
python ./cmsdetect.py 5 能代市 https://www.city.noshiro.lg.jp/
python ./cmsdetect.py 5 三種町 http://www.town.mitane.akita.jp/
python ./cmsdetect.py 5 八峰町 http://www.town.happou.akita.jp/
python ./cmsdetect.py 5 藤里町 http://www.town.fujisato.akita.jp/
python ./cmsdetect.py 5 秋田市 https://www.city.akita.lg.jp/
python ./cmsdetect.py 5 男鹿市 http://www.city.oga.akita.jp/
python ./cmsdetect.py 5 五城目町 http://www.town.gojome.akita.jp/
python ./cmsdetect.py 5 八郎潟町 https://www.town.hachirogata.akita.jp/
python ./cmsdetect.py 5 潟上市 https://www.city.katagami.lg.jp/
python ./cmsdetect.py 5 井川町 http://www.town.ikawa.akita.jp/
python ./cmsdetect.py 5 大潟村 http://www.ogata.or.jp/
python ./cmsdetect.py 5 由利本荘市 https://www.city.yurihonjo.lg.jp/
python ./cmsdetect.py 5 にかほ市 https://www.city.nikaho.akita.jp/
python ./cmsdetect.py 5 大仙市 https://www.city.daisen.lg.jp/
python ./cmsdetect.py 5 美郷町 https://www.town.misato.akita.jp/
python ./cmsdetect.py 5 仙北市 https://www.city.semboku.akita.jp/
python ./cmsdetect.py 5 横手市 https://www.city.yokote.lg.jp/
python ./cmsdetect.py 5 湯沢市 http://www.city-yuzawa.jp/
python ./cmsdetect.py 5 羽後町 https://www.town.ugo.lg.jp/
python ./cmsdetect.py 5 東成瀬村 http://www.higashinaruse.com/
