python ./cmsdetect.py 6 山形県 https://www.pref.yamagata.jp/
python ./cmsdetect.py 6 朝日町 https://www.town.asahi.yamagata.jp/
python ./cmsdetect.py 6 飯豊町 https://www.town.iide.yamagata.jp/
python ./cmsdetect.py 6 大石田町 http://www.town.oishida.yamagata.jp/
python ./cmsdetect.py 6 大江町 http://www.town.oe.yamagata.jp/
python ./cmsdetect.py 6 大蔵村 http://www.vill.ohkura.yamagata.jp/
python ./cmsdetect.py 6 小国町 http://www.town.oguni.yamagata.jp/
python ./cmsdetect.py 6 尾花沢市 http://www.city.obanazawa.yamagata.jp/
python ./cmsdetect.py 6 金山町 https://www.town.kaneyama.yamagata.jp/
python ./cmsdetect.py 6 上山市 https://www.city.kaminoyama.yamagata.jp/
python ./cmsdetect.py 6 河北町 https://www.town.kahoku.yamagata.jp/
python ./cmsdetect.py 6 川西町 https://www.town.kawanishi.yamagata.jp/
python ./cmsdetect.py 6 寒河江市 http://www.city.sagae.yamagata.jp/
python ./cmsdetect.py 6 酒田市 http://www.city.sakata.yamagata.jp/
python ./cmsdetect.py 6 鮭川村 http://www.vill.sakegawa.yamagata.jp/
python ./cmsdetect.py 6 庄内町 http://www.town.shonai.lg.jp/
python ./cmsdetect.py 6 白鷹町 http://www.town.shirataka.lg.jp/
python ./cmsdetect.py 6 新庄市 http://www.city.shinjo.yamagata.jp/
python ./cmsdetect.py 6 高畠町 https://www.town.takahata.yamagata.jp/
python ./cmsdetect.py 6 鶴岡市 http://www.city.tsuruoka.lg.jp/
python ./cmsdetect.py 6 天童市 https://www.city.tendo.yamagata.jp/
python ./cmsdetect.py 6 戸沢村 http://www.vill.tozawa.yamagata.jp/
python ./cmsdetect.py 6 長井市 http://www.city.nagai.yamagata.jp/
python ./cmsdetect.py 6 中山町 https://www.town.nakayama.yamagata.jp/
python ./cmsdetect.py 6 南陽市 http://www.city.nanyo.yamagata.jp/
python ./cmsdetect.py 6 西川町 http://www.town.nishikawa.yamagata.jp/
python ./cmsdetect.py 6 東根市 https://www.city.higashine.yamagata.jp/
python ./cmsdetect.py 6 舟形町 http://www.town.funagata.yamagata.jp/
python ./cmsdetect.py 6 真室川町 http://www.yume-net.org/
python ./cmsdetect.py 6 三川町 http://www.town.mikawa.yamagata.jp/
python ./cmsdetect.py 6 村山市 http://www.city.murayama.lg.jp/
python ./cmsdetect.py 6 最上町 https://mogami.tv/
python ./cmsdetect.py 6 山形市 http://www.city.yamagata-yamagata.lg.jp/
python ./cmsdetect.py 6 山辺町 https://www.town.yamanobe.yamagata.jp/
python ./cmsdetect.py 6 遊佐町 http://www.town.yuza.yamagata.jp/
python ./cmsdetect.py 6 米沢市 http://www.city.yonezawa.yamagata.jp/
