python ./cmsdetect.py 7 福島県 https://www.pref.fukushima.lg.jp
python ./cmsdetect.py 7 福島市 http://www.city.fukushima.fukushima.jp/
python ./cmsdetect.py 7 二本松市 https://www.city.nihonmatsu.lg.jp/
python ./cmsdetect.py 7 伊達市 https://www.city.fukushima-date.lg.jp/
python ./cmsdetect.py 7 本宮市 https://www.city.motomiya.lg.jp/
python ./cmsdetect.py 7 桑折町 http://www.town.koori.fukushima.jp/
python ./cmsdetect.py 7 国見町 https://www.town.kunimi.fukushima.jp/
python ./cmsdetect.py 7 川俣町 https://www.town.kawamata.lg.jp/
python ./cmsdetect.py 7 大玉村 https://www.vill.otama.fukushima.jp/
python ./cmsdetect.py 7 郡山市 https://www.city.koriyama.lg.jp/
python ./cmsdetect.py 7 須賀川市 https://www.city.sukagawa.fukushima.jp/
python ./cmsdetect.py 7 田村市 https://www.city.tamura.lg.jp/
python ./cmsdetect.py 7 鏡石町 https://www.town.kagamiishi.fukushima.jp/
python ./cmsdetect.py 7 天栄村 https://www.vill.tenei.fukushima.jp/
python ./cmsdetect.py 7 石川町 http://www.town.ishikawa.fukushima.jp/
python ./cmsdetect.py 7 玉川村 http://www.vill.tamakawa.fukushima.jp/
python ./cmsdetect.py 7 平田村 https://www.vill.hirata.fukushima.jp/
python ./cmsdetect.py 7 浅川町 http://www.town.asakawa.fukushima.jp/
python ./cmsdetect.py 7 古殿町 https://www.town.furudono.fukushima.jp/
python ./cmsdetect.py 7 三春町 https://www.town.miharu.fukushima.jp/
python ./cmsdetect.py 7 小野町 https://www.town.ono.fukushima.jp/
python ./cmsdetect.py 7 白河市 http://www.city.shirakawa.fukushima.jp/
python ./cmsdetect.py 7 西郷村 https://www.vill.nishigo.fukushima.jp/
python ./cmsdetect.py 7 泉崎村 https://www.vill.izumizaki.fukushima.jp/
python ./cmsdetect.py 7 中島村 http://www.vill-nakajima.jp/
python ./cmsdetect.py 7 矢吹町 http://www.town.yabuki.fukushima.jp/
python ./cmsdetect.py 7 棚倉町 http://www.town.tanagura.fukushima.jp/
python ./cmsdetect.py 7 矢祭町 http://www.town.yamatsuri.fukushima.jp/
python ./cmsdetect.py 7 塙町 http://www.town.hanawa.fukushima.jp/
python ./cmsdetect.py 7 鮫川村 https://www.vill.samegawa.fukushima.jp/
python ./cmsdetect.py 7 会津若松市 https://www.city.aizuwakamatsu.fukushima.jp/
python ./cmsdetect.py 7 喜多方市 http://www.city.kitakata.fukushima.jp/
python ./cmsdetect.py 7 北塩原村 https://www.vill.kitashiobara.fukushima.jp/
python ./cmsdetect.py 7 西会津町 https://www.town.nishiaizu.fukushima.jp/
python ./cmsdetect.py 7 磐梯町 https://www.town.bandai.fukushima.jp/
python ./cmsdetect.py 7 猪苗代町 http://www.town.inawashiro.fukushima.jp/
python ./cmsdetect.py 7 会津坂下町 https://www.town.aizubange.fukushima.jp/
python ./cmsdetect.py 7 湯川村 http://www.vill.yugawa.fukushima.jp/
python ./cmsdetect.py 7 柳津町 http://www.town.yanaizu.fukushima.jp/
python ./cmsdetect.py 7 三島町 http://www.town.mishima.fukushima.jp/
python ./cmsdetect.py 7 金山町 https://www.town.kaneyama.fukushima.jp/
python ./cmsdetect.py 7 昭和村 http://www.vill.showa.fukushima.jp/
python ./cmsdetect.py 7 会津美里町 https://www.town.aizumisato.fukushima.jp/
python ./cmsdetect.py 7 下郷町 https://www.town.shimogo.fukushima.jp/
python ./cmsdetect.py 7 檜枝岐村 https://www.vill.hinoemata.lg.jp/
python ./cmsdetect.py 7 只見町 https://www.town.tadami.lg.jp/
python ./cmsdetect.py 7 南会津町 http://www.minamiaizu.org/
python ./cmsdetect.py 7 相馬市 https://www.city.soma.fukushima.jp/
python ./cmsdetect.py 7 南相馬市 https://www.city.minamisoma.lg.jp/
python ./cmsdetect.py 7 広野町 https://www.town.hirono.fukushima.jp/
python ./cmsdetect.py 7 楢葉町 https://www.town.naraha.lg.jp/
python ./cmsdetect.py 7 富岡町 https://www.tomioka-town.jp/
python ./cmsdetect.py 7 川内村 http://www.kawauchimura.jp/
python ./cmsdetect.py 7 大熊町 https://www.town.okuma.fukushima.jp/
python ./cmsdetect.py 7 双葉町 https://www.town.fukushima-futaba.lg.jp/
python ./cmsdetect.py 7 浪江町 https://www.town.namie.fukushima.jp/
python ./cmsdetect.py 7 葛尾村 https://www.katsurao.org/
python ./cmsdetect.py 7 新地町 https://www.shinchi-town.jp/
python ./cmsdetect.py 7 飯舘村 https://www.vill.iitate.fukushima.jp/
python ./cmsdetect.py 7 いわき市 http://www.city.iwaki.lg.jp/