python ./cmsdetect.py 8 茨城県 https://www.pref.ibaraki.jp/
python ./cmsdetect.py 8 水戸市 https://www.city.mito.lg.jp/
python ./cmsdetect.py 8 日立市 https://www.city.hitachi.lg.jp/
python ./cmsdetect.py 8 土浦市 https://www.city.tsuchiura.lg.jp/
python ./cmsdetect.py 8 古河市 https://www.city.ibaraki-koga.lg.jp/
python ./cmsdetect.py 8 石岡市 http://www.city.ishioka.lg.jp/
python ./cmsdetect.py 8 結城市 https://www.city.yuki.lg.jp/
python ./cmsdetect.py 8 龍ケ崎市 http://www.city.ryugasaki.ibaraki.jp/
python ./cmsdetect.py 8 下妻市 https://www.city.shimotsuma.lg.jp/
python ./cmsdetect.py 8 常総市 http://www.city.joso.lg.jp/
python ./cmsdetect.py 8 常陸太田市 http://www.city.hitachiota.ibaraki.jp/
python ./cmsdetect.py 8 高萩市 https://www.city.takahagi.ibaraki.jp/
python ./cmsdetect.py 8 北茨城市 https://www.city.kitaibaraki.lg.jp/
python ./cmsdetect.py 8 笠間市 https://www.city.kasama.lg.jp/
python ./cmsdetect.py 8 取手市 http://www.city.toride.ibaraki.jp/
python ./cmsdetect.py 8 牛久市 http://www.city.ushiku.lg.jp/
python ./cmsdetect.py 8 つくば市 https://www.city.tsukuba.lg.jp/
python ./cmsdetect.py 8 ひたちなか市 http://www.city.hitachinaka.lg.jp/
python ./cmsdetect.py 8 鹿嶋市 https://www.city.kashima.ibaraki.jp/
python ./cmsdetect.py 8 潮来市 http://www.city.itako.lg.jp/
python ./cmsdetect.py 8 守谷市 https://www.city.moriya.ibaraki.jp/
python ./cmsdetect.py 8 常陸大宮市 https://www.city.hitachiomiya.lg.jp/
python ./cmsdetect.py 8 那珂市 https://www.city.naka.lg.jp/
python ./cmsdetect.py 8 筑西市 http://www.city.chikusei.lg.jp/
python ./cmsdetect.py 8 坂東市 http://www.city.bando.lg.jp/
python ./cmsdetect.py 8 稲敷市 https://www.city.inashiki.lg.jp/
python ./cmsdetect.py 8 かすみがうら市 http://www.city.kasumigaura.lg.jp/
python ./cmsdetect.py 8 桜川市 http://www.city.sakuragawa.lg.jp/
python ./cmsdetect.py 8 神栖市 https://www.city.kamisu.ibaraki.jp/
python ./cmsdetect.py 8 行方市 https://www.city.namegata.ibaraki.jp/
python ./cmsdetect.py 8 鉾田市 http://www.city.hokota.lg.jp/
python ./cmsdetect.py 8 つくばみらい市 https://www.city.tsukubamirai.lg.jp/
python ./cmsdetect.py 8 小美玉市 http://www.city.omitama.lg.jp/
python ./cmsdetect.py 8 茨城町 http://www.town.ibaraki.lg.jp/
python ./cmsdetect.py 8 大洗町 http://www.town.oarai.lg.jp/
python ./cmsdetect.py 8 城里町 https://www.town.shirosato.lg.jp/
python ./cmsdetect.py 8 東海村 https://www.vill.tokai.ibaraki.jp/index.html
python ./cmsdetect.py 8 大子町 https://www.town.daigo.ibaraki.jp/
python ./cmsdetect.py 8 美浦村 https://www.vill.miho.lg.jp/
python ./cmsdetect.py 8 阿見町 http://www.town.ami.lg.jp/
python ./cmsdetect.py 8 河内町 http://www.town.ibaraki-kawachi.lg.jp/
python ./cmsdetect.py 8 八千代町 http://www.town.ibaraki-yachiyo.lg.jp/
python ./cmsdetect.py 8 五霞町 https://www.town.goka.lg.jp/
python ./cmsdetect.py 8 境町 https://www.town.ibaraki-sakai.lg.jp/
python ./cmsdetect.py 8 利根町 http://www.town.tone.ibaraki.jp/
