python ./cmsdetect.py 9 栃木県 http://www.pref.tochigi.lg.jp/
python ./cmsdetect.py 9 宇都宮市 https://www.city.utsunomiya.tochigi.jp/
python ./cmsdetect.py 9 足利市 https://www.city.ashikaga.tochigi.jp/
python ./cmsdetect.py 9 栃木市 https://www.city.tochigi.lg.jp/
python ./cmsdetect.py 9 佐野市 https://www.city.sano.lg.jp/
python ./cmsdetect.py 9 鹿沼市 https://www.city.kanuma.tochigi.jp/
python ./cmsdetect.py 9 日光市 https://www.city.nikko.lg.jp/
python ./cmsdetect.py 9 小山市 https://www.city.oyama.tochigi.jp/
python ./cmsdetect.py 9 真岡市 https://www.city.moka.lg.jp/
python ./cmsdetect.py 9 大田原市 https://www.city.ohtawara.tochigi.jp/
python ./cmsdetect.py 9 矢板市 https://www.city.yaita.tochigi.jp/
python ./cmsdetect.py 9 那須塩原市 http://www.city.nasushiobara.lg.jp/
python ./cmsdetect.py 9 さくら市 http://www.city.tochigi-sakura.lg.jp/
python ./cmsdetect.py 9 那須烏山市 http://www.city.nasukarasuyama.lg.jp/
python ./cmsdetect.py 9 上三川町 https://www.town.kaminokawa.lg.jp/
python ./cmsdetect.py 9 益子町 http://www.town.mashiko.tochigi.jp/
python ./cmsdetect.py 9 茂木町 https://www.town.motegi.tochigi.jp/
python ./cmsdetect.py 9 市貝町 https://www.town.ichikai.tochigi.jp/
python ./cmsdetect.py 9 芳賀町 https://www.town.tochigi-haga.lg.jp/
python ./cmsdetect.py 9 壬生町 https://www.town.mibu.tochigi.jp/
python ./cmsdetect.py 9 野木町 http://www.town.nogi.lg.jp/
python ./cmsdetect.py 9 塩谷町 https://www.town.shioya.tochigi.jp/
python ./cmsdetect.py 9 高根沢町 https://www.town.takanezawa.tochigi.jp/
python ./cmsdetect.py 9 那須町 http://www.town.nasu.lg.jp/
python ./cmsdetect.py 9 那珂川町 http://www.town.tochigi-nakagawa.lg.jp/
